packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - core-js
  - esbuild
  - lefthook
  - prisma
  - sharp
  - unrs-resolver

patchedDependencies:
  '@scelar/nodepod@1.9.9': patches/@scelar__nodepod@1.9.9.patch
