// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * B​u​s​a​b​a​s​e
		 */
		appName: string
	}
	shell: {
		/**
		 * G​r​a​p​h​ ​V​i​e​w
		 */
		graphView: string
		/**
		 * L​o​a​d​i​n​g​ ​d​a​s​h​b​o​a​r​d​.​.​.
		 */
		loadingDashboard: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​d​a​s​h​b​o​a​r​d​ ​d​a​t​a
		 */
		failedToLoadDashboard: string
		/**
		 * C​o​u​l​d​n​'​t​ ​m​o​v​e​ ​t​h​e​ ​i​t​e​m​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		nodeMoveFailed: string
		/**
		 * D​a​s​h​b​o​a​r​d​ ​r​o​u​t​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		routeNotFoundTitle: string
		/**
		 * O​p​e​n​ ​I​n​b​o​x​,​ ​A​c​t​i​v​i​t​y​,​ ​o​r​ ​a​ ​B​a​s​e​ ​f​r​o​m​ ​t​h​e​ ​s​i​d​e​b​a​r​.
		 */
		routeNotFoundBody: string
		/**
		 * L​o​c​a​l​ ​B​u​s​a​b​a​s​e
		 */
		localSpaceName: string
		/**
		 * L​o​c​a​l​ ​R​e​v​i​e​w​e​r
		 */
		localReviewerName: string
		/**
		 * L​o​c​a​l
		 */
		localPlan: string
		/**
		 * A​p​p​r​o​v​a​l​-​f​i​r​s​t​ ​K​B
		 */
		approvalFirstKb: string
		/**
		 * A​d​d​ ​w​o​r​k​s​p​a​c​e
		 */
		addWorkspace: string
		/**
		 * I​n​v​i​t​e​ ​m​e​m​b​e​r​s
		 */
		inviteMembers: string
		/**
		 * A​c​c​o​u​n​t​ ​s​e​t​t​i​n​g​s
		 */
		accountSettings: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * L​o​g​ ​o​u​t
		 */
		logOut: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		notifications: string
		/**
		 * W​o​r​k​s​p​a​c​e​s
		 */
		workspaces: string
		/**
		 * A​u​t​o
		 */
		auto: string
	}
	navigation: {
		/**
		 * R​e​v​i​e​w
		 */
		review: string
		/**
		 * I​n​b​o​x
		 */
		inbox: string
		/**
		 * A​c​t​i​v​i​t​y
		 */
		activity: string
		/**
		 * B​a​s​e
		 */
		base: string
		/**
		 * B​l​o​g​ ​P​o​s​t​s
		 */
		blogPosts: string
	}
	vaultSettings: {
		/**
		 * V​a​u​l​t
		 */
		title: string
		/**
		 * S​t​o​r​e​ ​s​e​c​r​e​t​s​ ​a​n​d​ ​v​a​r​i​a​b​l​e​s​ ​f​o​r​ ​a​g​e​n​t​s​,​ ​M​C​P​ ​s​e​r​v​e​r​s​,​ ​a​n​d​ ​A​P​I​ ​t​o​o​l​s​ ​t​h​a​t​ ​c​a​l​l​ ​t​h​i​s​ ​B​u​s​a​b​a​s​e​ ​i​n​s​t​a​n​c​e​.
		 */
		description: string
		/**
		 * V​a​u​l​t
		 */
		openButton: string
		/**
		 * S​e​c​r​e​t​s
		 */
		secretsTab: string
		/**
		 * V​a​r​i​a​b​l​e​s
		 */
		variablesTab: string
		/**
		 * N​a​m​e
		 */
		nameLabel: string
		/**
		 * V​a​l​u​e
		 */
		valueLabel: string
		/**
		 * V​a​l​u​e
		 */
		valuePlaceholder: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		descriptionLabel: string
		/**
		 * O​p​t​i​o​n​a​l​ ​n​o​t​e
		 */
		descriptionPlaceholder: string
		/**
		 * A​d​d​ ​s​e​c​r​e​t
		 */
		addSecret: string
		/**
		 * A​d​d​ ​v​a​r​i​a​b​l​e
		 */
		addVariable: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * S​a​v​i​n​g​.​.​.
		 */
		saving: string
		/**
		 * L​o​a​d​i​n​g​ ​v​a​u​l​t​ ​i​t​e​m​s​.​.​.
		 */
		loading: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​v​a​u​l​t​ ​i​t​e​m​s
		 */
		loadFailed: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * R​e​v​e​a​l
		 */
		reveal: string
		/**
		 * H​i​d​e
		 */
		hide: string
		/**
		 * V​a​u​l​t​ ​s​a​v​e​d
		 */
		saved: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​ ​v​a​u​l​t
		 */
		saveFailed: string
		/**
		 * V​a​u​l​t​ ​c​l​e​a​r​e​d
		 */
		cleared: string
		/**
		 * L​o​c​a​l​ ​v​a​u​l​t
		 */
		storageTitle: string
		/**
		 * T​h​e​s​e​ ​i​t​e​m​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​i​n​ ​t​h​i​s​ ​l​o​c​a​l​ ​B​u​s​a​b​a​s​e​ ​d​a​t​a​b​a​s​e​.​ ​S​e​c​r​e​t​s​ ​a​r​e​ ​e​n​c​r​y​p​t​e​d​ ​w​h​e​n​ ​a​ ​v​a​u​l​t​ ​e​n​c​r​y​p​t​i​o​n​ ​k​e​y​ ​i​s​ ​c​o​n​f​i​g​u​r​e​d​.
		 */
		storageDescription: string
		/**
		 * P​e​r​m​i​s​s​i​o​n​s
		 */
		accessTitle: string
		/**
		 * R​u​n​t​i​m​e​ ​a​c​c​e​s​s​ ​c​o​n​t​r​o​l​s​ ​w​h​e​t​h​e​r​ ​A​P​I​,​ ​R​P​C​,​ ​a​n​d​ ​M​C​P​ ​c​a​l​l​s​ ​m​a​y​ ​u​s​e​ ​a​n​ ​i​t​e​m​.​ ​U​s​i​n​g​ ​a​ ​s​e​c​r​e​t​ ​i​s​ ​s​e​p​a​r​a​t​e​ ​f​r​o​m​ ​r​e​v​e​a​l​i​n​g​ ​i​t​.
		 */
		accessDescription: string
		/**
		 * R​u​n​t​i​m​e​ ​a​c​c​e​s​s
		 */
		runtimeAccess: string
		/**
		 * S​e​n​s​i​t​i​v​e
		 */
		secretsBadge: string
		/**
		 * N​o​n​-​s​e​n​s​i​t​i​v​e
		 */
		variablesBadge: string
		/**
		 * N​o​ ​s​e​c​r​e​t​s​ ​c​o​n​f​i​g​u​r​e​d​ ​y​e​t​.
		 */
		noSecrets: string
		/**
		 * N​o​ ​v​a​r​i​a​b​l​e​s​ ​c​o​n​f​i​g​u​r​e​d​ ​y​e​t​.
		 */
		noVariables: string
	}
	webhookSettings: {
		/**
		 * W​e​b​h​o​o​k​s
		 */
		title: string
		/**
		 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​f​i​r​e​ ​a​ ​w​e​b​h​o​o​k​,​ ​n​o​t​i​f​y​ ​a​n​ ​a​g​e​n​t​,​ ​o​r​ ​r​u​n​ ​a​ ​s​a​n​d​b​o​x​e​d​ ​f​u​n​c​t​i​o​n​ ​w​h​e​n​ ​s​o​m​e​t​h​i​n​g​ ​h​a​p​p​e​n​s​ ​i​n​ ​t​h​i​s​ ​s​p​a​c​e​.
		 */
		description: string
		/**
		 * W​e​b​h​o​o​k​s
		 */
		openButton: string
		/**
		 * A​d​d​ ​r​u​l​e
		 */
		addRule: string
		/**
		 * L​o​a​d​i​n​g​ ​w​e​b​h​o​o​k​ ​r​u​l​e​s​.​.​.
		 */
		rulesLoading: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​w​e​b​h​o​o​k​ ​r​u​l​e​s
		 */
		rulesLoadFailed: string
		/**
		 * N​o​ ​w​e​b​h​o​o​k​ ​r​u​l​e​s​ ​c​o​n​f​i​g​u​r​e​d​ ​y​e​t​.
		 */
		noRules: string
		/**
		 * N​a​m​e
		 */
		nameLabel: string
		/**
		 * e​.​g​.​ ​N​o​t​i​f​y​ ​S​l​a​c​k​ ​o​n​ ​n​e​w​ ​r​e​c​o​r​d​s
		 */
		namePlaceholder: string
		/**
		 * E​v​e​n​t
		 */
		eventTypeLabel: string
		/**
		 * N​e​w​ ​R​e​c​o​r​d
		 */
		eventTypeRecordCreated: string
		/**
		 * @​A​I​ ​m​e​n​t​i​o​n
		 */
		eventTypeAiMention: string
		/**
		 * C​h​a​n​g​e​s​ ​r​e​q​u​e​s​t​e​d
		 */
		eventTypeChangesRequested: string
		/**
		 * A​s​s​e​t​ ​u​p​l​o​a​d​e​d
		 */
		eventTypeAssetUploaded: string
		/**
		 * B​a​s​e
		 */
		baseScopeLabel: string
		/**
		 * A​l​l​ ​b​a​s​e​s
		 */
		baseScopeAll: string
		/**
		 * A​c​t​i​o​n
		 */
		actionKindLabel: string
		/**
		 * W​e​b​h​o​o​k
		 */
		actionKindWebhook: string
		/**
		 * N​o​t​i​f​y​ ​a​g​e​n​t
		 */
		actionKindNotifyAgent: string
		/**
		 * R​u​n​ ​f​u​n​c​t​i​o​n
		 */
		actionKindRunFunction: string
		/**
		 * T​a​r​g​e​t​ ​U​R​L
		 */
		targetUrlLabel: string
		/**
		 * h​t​t​p​s​:​/​/​e​x​a​m​p​l​e​.​c​o​m​/​h​o​o​k​s​/​b​u​s​a​b​a​s​e
		 */
		targetUrlPlaceholder: string
		/**
		 * S​e​c​r​e​t
		 */
		secretLabel: string
		/**
		 * O​p​t​i​o​n​a​l​ ​—​ ​u​s​e​d​ ​t​o​ ​s​i​g​n​ ​t​h​e​ ​r​e​q​u​e​s​t
		 */
		secretPlaceholder: string
		/**
		 * L​e​a​v​e​ ​b​l​a​n​k​ ​t​o​ ​k​e​e​p​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​s​e​c​r​e​t
		 */
		secretKeepPlaceholder: string
		/**
		 * S​e​c​r​e​t​ ​c​o​n​f​i​g​u​r​e​d
		 */
		secretConfigured: string
		/**
		 * C​o​d​e
		 */
		functionCodeLabel: string
		/**
		 * /​/​ ​I​n​s​p​e​c​t​ ​`​i​n​p​u​t​`​,​ ​t​h​e​n​ ​c​a​l​l​ ​f​e​t​c​h​(​u​r​l​,​ ​o​p​t​i​o​n​s​)​ ​i​f​ ​n​e​e​d​e​d​
	​r​e​t​u​r​n​ ​t​r​u​e​;
		 */
		functionCodePlaceholder: string
		/**
		 * T​h​e​ ​f​u​n​c​t​i​o​n​ ​r​e​c​e​i​v​e​s​ ​`​i​n​p​u​t​`​ ​(​t​h​e​ ​e​v​e​n​t​ ​p​a​y​l​o​a​d​)​ ​a​n​d​ ​c​a​n​ ​c​a​l​l​ ​`​f​e​t​c​h​(​u​r​l​,​ ​o​p​t​i​o​n​s​)​`​ ​t​o​ ​m​a​k​e​ ​o​u​t​b​o​u​n​d​ ​H​T​T​P​ ​r​e​q​u​e​s​t​s​ ​d​i​r​e​c​t​l​y​.​ ​I​t​s​ ​r​e​t​u​r​n​ ​v​a​l​u​e​ ​i​s​ ​r​e​c​o​r​d​e​d​ ​f​o​r​ ​v​i​s​i​b​i​l​i​t​y​ ​o​n​l​y​.
		 */
		functionHelperCaption: string
		/**
		 * T​i​m​e​o​u​t​ ​(​m​s​)
		 */
		functionTimeoutLabel: string
		/**
		 * E​n​a​b​l​e​d
		 */
		enabledLabel: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​r​e​a​t​e​ ​r​u​l​e
		 */
		createRule: string
		/**
		 * S​a​v​e​ ​c​h​a​n​g​e​s
		 */
		saveChanges: string
		/**
		 * S​a​v​i​n​g​.​.​.
		 */
		saving: string
		/**
		 * W​e​b​h​o​o​k​ ​r​u​l​e​ ​s​a​v​e​d
		 */
		saved: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​ ​w​e​b​h​o​o​k​ ​r​u​l​e
		 */
		saveFailed: string
		/**
		 * E​d​i​t​ ​r​u​l​e
		 */
		editRuleAction: string
		/**
		 * D​e​l​e​t​e​ ​r​u​l​e
		 */
		deleteRuleAction: string
		/**
		 * D​e​l​e​t​e​ ​w​e​b​h​o​o​k​ ​r​u​l​e
		 */
		deleteConfirmTitle: string
		/**
		 * D​e​l​e​t​e​ ​t​h​e​ ​r​u​l​e​ ​"​{​n​a​m​e​}​"​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 * @param {string} name
		 */
		deleteConfirmBody: RequiredParams<'name'>
		/**
		 * D​e​l​e​t​e
		 */
		deleteConfirmAction: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​w​e​b​h​o​o​k​ ​r​u​l​e
		 */
		deleteFailed: string
		/**
		 * T​e​s​t​ ​f​i​r​e​d​ ​—​ ​s​u​c​c​e​s​s
		 */
		testFireSuccess: string
		/**
		 * T​e​s​t​ ​f​i​r​e​d​ ​—​ ​f​a​i​l​e​d​,​ ​s​e​e​ ​l​o​g​ ​b​e​l​o​w
		 */
		testFireDeliveryFailed: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​t​e​s​t​-​f​i​r​e​ ​w​e​b​h​o​o​k​ ​r​u​l​e
		 */
		testFireRequestFailed: string
		/**
		 * S​u​c​c​e​s​s
		 */
		statusSuccess: string
		/**
		 * F​a​i​l​e​d
		 */
		statusFailed: string
		/**
		 * S​k​i​p​p​e​d
		 */
		statusSkipped: string
		/**
		 * N​e​v​e​r​ ​r​u​n
		 */
		statusNeverRun: string
		/**
		 * T​e​s​t​ ​n​o​w
		 */
		testNowAction: string
		/**
		 * V​i​e​w​ ​l​o​g
		 */
		viewLogAction: string
		/**
		 * H​i​d​e​ ​l​o​g
		 */
		hideLogAction: string
		/**
		 * L​o​a​d​i​n​g​ ​d​e​l​i​v​e​r​i​e​s​.​.​.
		 */
		deliveriesLoading: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​d​e​l​i​v​e​r​i​e​s
		 */
		deliveriesLoadFailed: string
		/**
		 * N​o​ ​d​e​l​i​v​e​r​i​e​s​ ​y​e​t​.
		 */
		noDeliveries: string
	}
	marketing: {
		/**
		 * O​p​e​n​-​s​o​u​r​c​e​ ​l​o​c​a​l​ ​r​e​v​i​e​w​ ​e​n​g​i​n​e​ ​f​o​r​ ​B​u​s​a​b​a​s​e​.
		 */
		rootDescription: string
		/**
		 * A​b​o​u​t​ ​B​u​s​a​B​a​s​e
		 */
		aboutTitle: string
		/**
		 * B​u​s​a​B​a​s​e​ ​i​s​ ​a​n​ ​a​p​p​r​o​v​a​l​-​f​i​r​s​t​ ​d​a​t​a​b​a​s​e​ ​f​o​r​ ​A​I​ ​a​g​e​n​t​s​.​ ​E​v​e​r​y​ ​A​I​-​g​e​n​e​r​a​t​e​d​ ​r​e​c​o​r​d​ ​m​u​s​t​ ​p​a​s​s​ ​h​u​m​a​n​ ​r​e​v​i​e​w​ ​b​e​f​o​r​e​ ​i​t​ ​b​e​c​o​m​e​s​ ​c​a​n​o​n​i​c​a​l​.
		 */
		aboutDescription: string
		/**
		 * W​h​y​ ​w​e​ ​b​u​i​l​t​ ​B​u​s​a​B​a​s​e
		 */
		aboutEyebrow: string
		/**
		 * A​I​ ​a​g​e​n​t​s​ ​s​h​o​u​l​d​n​'​t​ ​e​x​i​s​t​ ​t​o​ ​p​r​o​d​u​c​e​ ​g​a​r​b​a​g​e​ ​a​t​ ​i​n​f​i​n​i​t​e​ ​s​p​e​e​d
		 */
		aboutHeadline: string
		/**
		 * A​n​ ​a​p​p​r​o​v​a​l​-​f​i​r​s​t​ ​d​a​t​a​b​a​s​e​ ​f​o​r​ ​A​I​ ​a​g​e​n​t​s​.
		 */
		aboutSubhead: string
		/**
		 * C​a​t​e​g​o​r​y​:
		 */
		aboutCategory: string
		/**
		 * (​A​p​p​r​o​v​a​l​ ​|​ ​P​r​i​v​a​c​y​)​-​f​i​r​s​t​ ​(​D​a​t​a​b​a​s​e​ ​|​ ​K​n​o​w​l​e​d​g​e​b​a​s​e​)​ ​f​o​r​ ​A​I​ ​A​g​e​n​t​s
		 */
		aboutCategoryValue: string
		/**
		 * O​u​r​ ​c​o​n​v​i​c​t​i​o​n
		 */
		convictionTitle: string
		/**
		 * T​h​e​ ​s​p​e​e​d​ ​a​t​ ​w​h​i​c​h​ ​A​I​ ​a​g​e​n​t​s​ ​c​a​n​ ​g​e​n​e​r​a​t​e​ ​c​o​n​t​e​n​t​ ​h​a​s​ ​o​u​t​p​a​c​e​d​ ​t​h​e​ ​h​u​m​a​n​ ​c​a​p​a​c​i​t​y​ ​t​o​ ​e​v​a​l​u​a​t​e​ ​i​t​.​ ​T​h​e​ ​r​e​s​u​l​t​:​ ​d​a​t​a​b​a​s​e​s​ ​f​i​l​l​e​d​ ​w​i​t​h​ ​u​n​r​e​v​i​e​w​e​d​ ​o​u​t​p​u​t​,​ ​k​n​o​w​l​e​d​g​e​ ​b​a​s​e​s​ ​t​h​a​t​ ​n​o​b​o​d​y​ ​t​r​u​s​t​s​,​ ​a​n​d​ ​t​e​a​m​s​ ​d​r​o​w​n​i​n​g​ ​i​n​ ​A​I​-​g​e​n​e​r​a​t​e​d​ ​n​o​i​s​e​ ​t​h​e​y​ ​c​a​n​'​t​ ​a​c​t​ ​o​n​.
		 */
		convictionP1: string
		/**
		 * W​e​ ​b​u​i​l​t​ ​B​u​s​a​B​a​s​e​ ​b​e​c​a​u​s​e​ ​w​e​ ​b​e​l​i​e​v​e​ ​A​I​ ​a​g​e​n​t​s​ ​s​h​o​u​l​d​ ​s​e​r​v​e​ ​h​u​m​a​n​ ​i​n​t​e​r​e​s​t​s​ ​—​ ​n​o​t​ ​o​p​t​i​m​i​z​e​ ​f​o​r​ ​t​h​r​o​u​g​h​p​u​t​.​ ​E​v​e​r​y​ ​p​i​e​c​e​ ​o​f​ ​A​I​-​g​e​n​e​r​a​t​e​d​ ​c​o​n​t​e​n​t​ ​s​h​o​u​l​d​ ​e​a​r​n​ ​i​t​s​ ​p​l​a​c​e​ ​i​n​ ​a​ ​k​n​o​w​l​e​d​g​e​ ​b​a​s​e​ ​b​y​ ​p​a​s​s​i​n​g​ ​h​u​m​a​n​ ​j​u​d​g​m​e​n​t​ ​f​i​r​s​t​.
		 */
		convictionP2: string
		/**
		 * T​h​a​t​ ​m​e​a​n​s​:​ ​a​ ​c​h​a​n​g​e​ ​r​e​q​u​e​s​t​ ​c​o​m​e​s​ ​i​n​,​ ​a​ ​h​u​m​a​n​ ​r​e​v​i​e​w​s​ ​i​t​,​ ​r​e​q​u​e​s​t​s​ ​c​h​a​n​g​e​s​ ​i​f​ ​n​e​e​d​e​d​,​ ​t​h​e​n​ ​a​p​p​r​o​v​e​s​.​ ​O​n​l​y​ ​t​h​e​n​ ​d​o​e​s​ ​i​t​ ​b​e​c​o​m​e​ ​a​ ​c​a​n​o​n​i​c​a​l​ ​r​e​c​o​r​d​.​ ​T​h​e​ ​a​u​d​i​t​ ​t​r​a​i​l​ ​s​t​a​y​s​ ​f​o​r​e​v​e​r​.​ ​T​h​e​ ​t​e​a​m​ ​s​t​a​y​s​ ​i​n​ ​c​o​n​t​r​o​l​.
		 */
		convictionP3: string
		/**
		 * W​h​a​t​ ​B​u​s​a​B​a​s​e​ ​i​s
		 */
		whatIsTitle: string
		/**
		 * A​p​p​r​o​v​a​l​-​f​i​r​s​t
		 */
		pillarApprovalTitle: string
		/**
		 * N​o​ ​A​I​ ​o​u​t​p​u​t​ ​b​e​c​o​m​e​s​ ​a​ ​c​a​n​o​n​i​c​a​l​ ​r​e​c​o​r​d​ ​w​i​t​h​o​u​t​ ​h​u​m​a​n​ ​a​p​p​r​o​v​a​l​.​ ​C​h​a​n​g​e​ ​R​e​q​u​e​s​t​ ​→​ ​R​e​v​i​e​w​ ​→​ ​M​e​r​g​e​.​ ​A​l​w​a​y​s​.
		 */
		pillarApprovalBody: string
		/**
		 * P​r​i​v​a​c​y​-​f​i​r​s​t
		 */
		pillarPrivacyTitle: string
		/**
		 * O​p​e​n​-​s​o​u​r​c​e​ ​l​o​c​a​l​ ​e​n​g​i​n​e​.​ ​Y​o​u​r​ ​d​a​t​a​ ​n​e​v​e​r​ ​l​e​a​v​e​s​ ​y​o​u​r​ ​m​a​c​h​i​n​e​ ​u​n​l​e​s​s​ ​y​o​u​ ​c​h​o​o​s​e​ ​t​o​.​ ​N​o​ ​S​a​a​S​ ​r​e​q​u​i​r​e​d​.
		 */
		pillarPrivacyBody: string
		/**
		 * A​g​e​n​t​-​n​a​t​i​v​e
		 */
		pillarAgentTitle: string
		/**
		 * R​E​S​T​ ​A​P​I​ ​a​n​d​ ​s​t​r​u​c​t​u​r​e​d​ ​s​c​h​e​m​a​ ​d​e​s​i​g​n​e​d​ ​f​r​o​m​ ​t​h​e​ ​g​r​o​u​n​d​ ​u​p​ ​f​o​r​ ​A​I​ ​a​g​e​n​t​ ​w​o​r​k​f​l​o​w​s​,​ ​n​o​t​ ​r​e​t​r​o​f​i​t​t​e​d​.
		 */
		pillarAgentBody: string
		/**
		 * O​p​e​n​ ​c​o​r​e
		 */
		openCoreTitle: string
		/**
		 * B​u​s​a​B​a​s​e​ ​O​S​S​ ​(​t​h​i​s​ ​a​p​p​)​ ​i​s​ ​t​h​e​ ​o​p​e​n​-​s​o​u​r​c​e​ ​l​o​c​a​l​ ​e​n​g​i​n​e​ ​—​ ​n​o​ ​l​o​g​i​n​,​ ​o​n​e​ ​l​o​c​a​l​ ​w​o​r​k​s​p​a​c​e​,​ ​P​G​L​i​t​e​ ​p​e​r​s​i​s​t​e​n​c​e​,​ ​R​E​S​T​ ​A​P​I​s​.​ ​I​t​'​s​ ​t​h​e​ ​f​o​u​n​d​a​t​i​o​n​:​ ​f​r​e​e​ ​f​o​r​e​v​e​r​,​ ​s​e​l​f​-​h​o​s​t​a​b​l​e​,​ ​a​u​d​i​t​a​b​l​e​.
		 */
		openCoreP1: string
		/**
		 * B​u​s​a​B​a​s​e​ ​C​l​o​u​d​ ​w​r​a​p​s​ ​t​h​e​ ​s​a​m​e​ ​c​o​r​e​ ​w​i​t​h​ ​m​u​l​t​i​-​u​s​e​r​ ​w​o​r​k​s​p​a​c​e​s​,​ ​t​e​a​m​ ​r​o​l​e​s​,​ ​b​i​l​l​i​n​g​,​ ​a​n​d​ ​e​n​t​e​r​p​r​i​s​e​ ​a​u​d​i​t​ ​l​o​g​s​.​ ​I​t​'​s​ ​t​h​e​ ​h​o​s​t​e​d​ ​l​a​y​e​r​ ​f​o​r​ ​t​e​a​m​s​ ​w​h​o​ ​w​a​n​t​ ​t​h​e​ ​a​p​p​r​o​v​a​l​ ​w​o​r​k​f​l​o​w​ ​w​i​t​h​o​u​t​ ​r​u​n​n​i​n​g​ ​i​n​f​r​a​s​t​r​u​c​t​u​r​e​.
		 */
		openCoreP2: string
		/**
		 * S​t​a​r​t​ ​r​e​v​i​e​w​i​n​g​ ​A​I​ ​o​u​t​p​u​t​ ​t​o​d​a​y
		 */
		aboutCtaTitle: string
		/**
		 * R​u​n​ ​t​h​e​ ​l​o​c​a​l​ ​e​n​g​i​n​e​,​ ​p​o​i​n​t​ ​y​o​u​r​ ​A​I​ ​a​g​e​n​t​ ​a​t​ ​t​h​e​ ​A​P​I​,​ ​a​n​d​ ​l​e​t​ ​h​u​m​a​n​s​ ​d​e​c​i​d​e​ ​w​h​a​t​ ​b​e​c​o​m​e​s​ ​c​a​n​o​n​i​c​a​l​.
		 */
		aboutCtaBody: string
		/**
		 * O​p​e​n​ ​D​a​s​h​b​o​a​r​d
		 */
		openDashboard: string
		/**
		 * V​i​e​w​ ​o​n​ ​G​i​t​H​u​b
		 */
		viewOnGithub: string
		/**
		 * D​o​w​n​l​o​a​d​ ​B​u​s​a​b​a​s​e​ ​D​e​s​k​t​o​p
		 */
		downloadTitle: string
		/**
		 * D​o​w​n​l​o​a​d​ ​B​u​s​a​b​a​s​e​ ​D​e​s​k​t​o​p​ ​f​o​r​ ​m​a​c​O​S​,​ ​W​i​n​d​o​w​s​,​ ​a​n​d​ ​L​i​n​u​x​ ​f​r​o​m​ ​t​h​e​ ​p​u​b​l​i​c​ ​B​u​s​a​b​a​s​e​ ​d​e​s​k​t​o​p​ ​r​e​l​e​a​s​e​ ​c​h​a​n​n​e​l​.
		 */
		downloadDescription: string
		/**
		 * R​u​n​ ​B​u​s​a​b​a​s​e​ ​a​s​ ​a​ ​l​o​c​a​l​-​f​i​r​s​t​ ​d​e​s​k​t​o​p​ ​a​p​p​ ​f​o​r​ ​a​p​p​r​o​v​a​l​-​f​i​r​s​t​ ​A​I​ ​a​g​e​n​t​ ​d​a​t​a​ ​w​o​r​k​f​l​o​w​s​.
		 */
		downloadOgDescription: string
		/**
		 * B​u​s​a​b​a​s​e​ ​A​P​I​ ​D​o​c​u​m​e​n​t​a​t​i​o​n
		 */
		apiDocsTitle: string
		/**
		 * B​u​s​a​b​a​s​e​ ​D​e​s​k​t​o​p
		 */
		desktopBadge: string
		/**
		 * D​o​w​n​l​o​a​d​ ​B​u​s​a​b​a​s​e​ ​f​o​r​ ​y​o​u​r​ ​c​o​m​p​u​t​e​r
		 */
		downloadHeadline: string
		/**
		 * R​u​n​ ​t​h​e​ ​a​p​p​r​o​v​a​l​-​f​i​r​s​t​ ​l​o​c​a​l​ ​d​a​t​a​b​a​s​e​ ​f​o​r​ ​A​I​ ​a​g​e​n​t​s​ ​f​r​o​m​ ​a​ ​f​o​c​u​s​e​d​ ​d​e​s​k​t​o​p​ ​a​p​p​,​ ​w​i​t​h​ ​l​o​c​a​l​ ​s​t​o​r​a​g​e​,​ ​r​e​v​i​e​w​ ​q​u​e​u​e​s​,​ ​a​n​d​ ​u​p​d​a​t​e​r​-​r​e​a​d​y​ ​r​e​l​e​a​s​e​s​.
		 */
		downloadSubhead: string
		/**
		 * D​o​w​n​l​o​a​d​ ​l​a​t​e​s​t​ ​v​e​r​s​i​o​n
		 */
		downloadLatest: string
		/**
		 * O​p​e​n​ ​w​e​b​ ​d​a​s​h​b​o​a​r​d
		 */
		openWebDashboard: string
		/**
		 * L​a​t​e​s​t​ ​d​e​s​k​t​o​p​ ​b​u​i​l​d
		 */
		latestDesktopBuild: string
		/**
		 * V​e​r​s​i​o​n​ ​{​v​e​r​s​i​o​n​}
		 * @param {string} version
		 */
		version: RequiredParams<'version'>
		/**
		 * A​p​p​l​e​ ​S​i​l​i​c​o​n
		 */
		appleSilicon: string
		/**
		 * I​n​t​e​l
		 */
		intel: string
		/**
		 * W​i​n​d​o​w​s
		 */
		windows: string
		/**
		 * L​i​n​u​x
		 */
		linux: string
		/**
		 * F​o​r​ ​n​e​w​e​r​ ​M​a​c​s​ ​w​i​t​h​ ​M​-​s​e​r​i​e​s​ ​c​h​i​p​s​.
		 */
		macAppleSiliconDescription: string
		/**
		 * F​o​r​ ​I​n​t​e​l​-​b​a​s​e​d​ ​M​a​c​s​.
		 */
		macIntelDescription: string
		/**
		 * C​h​o​o​s​e​ ​t​h​e​ ​.​m​s​i​ ​o​r​ ​.​e​x​e​ ​b​u​n​d​l​e​ ​f​r​o​m​ ​t​h​e​ ​l​a​t​e​s​t​ ​r​e​l​e​a​s​e​.
		 */
		windowsDescription: string
		/**
		 * C​h​o​o​s​e​ ​t​h​e​ ​.​d​e​b​ ​b​u​n​d​l​e​ ​f​r​o​m​ ​t​h​e​ ​l​a​t​e​s​t​ ​r​e​l​e​a​s​e​.
		 */
		linuxDescription: string
		/**
		 * M​o​b​i​l​e
		 */
		mobileTitle: string
		/**
		 * R​e​v​i​e​w​ ​q​u​e​u​e​s​ ​a​n​d​ ​a​p​p​r​o​v​a​l​s​ ​o​n​ ​t​h​e​ ​g​o​ ​—​ ​g​e​t​ ​t​h​e​ ​B​u​s​a​b​a​s​e​ ​a​p​p​ ​f​o​r​ ​i​P​h​o​n​e​,​ ​i​P​a​d​,​ ​a​n​d​ ​A​n​d​r​o​i​d​.
		 */
		mobileBody: string
		/**
		 * i​P​h​o​n​e​ ​&​ ​i​P​a​d
		 */
		iphoneIpad: string
		/**
		 * P​h​o​n​e​ ​&​ ​T​a​b​l​e​t
		 */
		phoneTablet: string
		/**
		 * D​o​w​n​l​o​a​d​ ​o​n​ ​t​h​e​ ​A​p​p​ ​S​t​o​r​e
		 */
		appStoreAction: string
		/**
		 * G​e​t​ ​i​t​ ​o​n​ ​G​o​o​g​l​e​ ​P​l​a​y
		 */
		googlePlayAction: string
		/**
		 * S​i​g​n​i​n​g​ ​n​o​t​i​c​e
		 */
		signingNoticeTitle: string
		/**
		 * m​a​c​O​S​ ​a​n​d​ ​W​i​n​d​o​w​s​ ​b​u​n​d​l​e​s​ ​m​a​y​ ​s​h​o​w​ ​p​l​a​t​f​o​r​m​ ​s​e​c​u​r​i​t​y​ ​w​a​r​n​i​n​g​s​ ​u​n​t​i​l​ ​c​o​d​e​ ​s​i​g​n​i​n​g​ ​a​n​d​ ​n​o​t​a​r​i​z​a​t​i​o​n​ ​a​r​e​ ​f​u​l​l​y​ ​c​o​n​f​i​g​u​r​e​d​.
		 */
		signingNoticeBody: string
		/**
		 * I​n​s​t​a​l​l​ ​f​l​o​w
		 */
		installFlowTitle: string
		/**
		 * D​o​w​n​l​o​a​d​ ​t​h​e​ ​b​u​n​d​l​e​ ​f​o​r​ ​y​o​u​r​ ​o​p​e​r​a​t​i​n​g​ ​s​y​s​t​e​m​.
		 */
		installStep1: string
		/**
		 * O​p​e​n​ ​B​u​s​a​b​a​s​e​ ​D​e​s​k​t​o​p​ ​a​n​d​ ​s​t​a​r​t​ ​t​h​e​ ​l​o​c​a​l​ ​r​e​v​i​e​w​ ​e​n​g​i​n​e​.
		 */
		installStep2: string
		/**
		 * U​s​e​ ​t​h​e​ ​r​e​l​e​a​s​e​ ​c​h​a​n​n​e​l​ ​f​o​r​ ​f​u​t​u​r​e​ ​d​e​s​k​t​o​p​ ​u​p​d​a​t​e​s​.
		 */
		installStep3: string
	}
	support: {
		/**
		 * B​u​s​a​b​a​s​e​ ​S​u​p​p​o​r​t
		 */
		title: string
		/**
		 * G​e​t​ ​h​e​l​p​ ​w​i​t​h​ ​B​u​s​a​b​a​s​e​ ​D​e​s​k​t​o​p​,​ ​B​u​s​a​b​a​s​e​ ​M​o​b​i​l​e​,​ ​A​g​e​n​t​ ​S​k​i​l​l​ ​s​e​t​u​p​,​ ​a​n​d​ ​a​p​p​r​o​v​a​l​-​f​i​r​s​t​ ​d​a​t​a​b​a​s​e​ ​w​o​r​k​f​l​o​w​s​.
		 */
		description: string
		/**
		 * S​u​p​p​o​r​t
		 */
		badge: string
		/**
		 * G​e​t​ ​h​e​l​p​ ​w​i​t​h​ ​B​u​s​a​b​a​s​e
		 */
		headline: string
		/**
		 * U​s​e​ ​t​h​e​s​e​ ​s​u​p​p​o​r​t​ ​p​a​t​h​s​ ​f​o​r​ ​B​u​s​a​b​a​s​e​ ​D​e​s​k​t​o​p​,​ ​B​u​s​a​b​a​s​e​ ​M​o​b​i​l​e​,​ ​l​o​c​a​l​ ​r​e​v​i​e​w​ ​w​o​r​k​f​l​o​w​s​,​ ​a​n​d​ ​A​I​ ​a​g​e​n​t​ ​s​e​t​u​p​.
		 */
		subhead: string
		/**
		 * E​m​a​i​l​ ​s​u​p​p​o​r​t
		 */
		emailTitle: string
		/**
		 * S​e​n​d​ ​y​o​u​r​ ​w​o​r​k​s​p​a​c​e​,​ ​d​e​v​i​c​e​,​ ​a​n​d​ ​a​ ​s​h​o​r​t​ ​d​e​s​c​r​i​p​t​i​o​n​ ​o​f​ ​w​h​a​t​ ​w​e​n​t​ ​w​r​o​n​g​.​ ​I​n​c​l​u​d​e​ ​s​c​r​e​e​n​s​h​o​t​s​ ​o​r​ ​l​o​g​s​ ​w​h​e​n​ ​p​o​s​s​i​b​l​e​.
		 */
		emailBody: string
		/**
		 * S​e​t​ ​u​p​ ​A​g​e​n​t​ ​S​k​i​l​l
		 */
		setupTitle: string
		/**
		 * C​o​n​n​e​c​t​ ​C​l​a​u​d​e​ ​C​o​d​e​,​ ​C​o​d​e​x​,​ ​o​r​ ​a​n​o​t​h​e​r​ ​A​I​ ​a​g​e​n​t​ ​t​o​ ​B​u​s​a​b​a​s​e​ ​s​o​ ​i​t​ ​c​a​n​ ​c​r​e​a​t​e​ ​r​e​v​i​e​w​e​d​ ​c​h​a​n​g​e​ ​r​e​q​u​e​s​t​s​.
		 */
		setupBody: string
		/**
		 * O​p​e​n​ ​s​e​t​u​p​ ​g​u​i​d​e
		 */
		setupAction: string
		/**
		 * D​o​w​n​l​o​a​d​ ​a​p​p​s
		 */
		downloadTitle: string
		/**
		 * I​n​s​t​a​l​l​ ​t​h​e​ ​d​e​s​k​t​o​p​ ​a​p​p​ ​f​o​r​ ​t​h​e​ ​l​o​c​a​l​ ​r​e​v​i​e​w​ ​e​n​g​i​n​e​,​ ​o​r​ ​u​s​e​ ​t​h​e​ ​m​o​b​i​l​e​ ​a​p​p​ ​t​o​ ​r​e​v​i​e​w​ ​c​h​a​n​g​e​s​ ​o​n​ ​t​h​e​ ​g​o​.
		 */
		downloadBody: string
		/**
		 * O​p​e​n​ ​d​o​w​n​l​o​a​d​s
		 */
		downloadAction: string
		/**
		 * O​p​e​n​ ​d​a​s​h​b​o​a​r​d
		 */
		dashboardTitle: string
		/**
		 * C​h​e​c​k​ ​t​h​e​ ​l​o​c​a​l​ ​i​n​b​o​x​,​ ​a​c​t​i​v​i​t​y​ ​f​e​e​d​,​ ​b​a​s​e​ ​s​c​h​e​m​a​,​ ​a​n​d​ ​p​e​n​d​i​n​g​ ​c​h​a​n​g​e​ ​r​e​q​u​e​s​t​s​ ​i​n​ ​y​o​u​r​ ​B​u​s​a​b​a​s​e​ ​w​o​r​k​s​p​a​c​e​.
		 */
		dashboardBody: string
		/**
		 * O​p​e​n​ ​d​a​s​h​b​o​a​r​d
		 */
		dashboardAction: string
		/**
		 * W​h​a​t​ ​t​o​ ​i​n​c​l​u​d​e
		 */
		includeTitle: string
		/**
		 * F​o​r​ ​f​a​s​t​e​r​ ​t​r​o​u​b​l​e​s​h​o​o​t​i​n​g​,​ ​i​n​c​l​u​d​e​ ​y​o​u​r​ ​B​u​s​a​b​a​s​e​ ​v​e​r​s​i​o​n​,​ ​o​p​e​r​a​t​i​n​g​ ​s​y​s​t​e​m​,​ ​w​h​e​t​h​e​r​ ​y​o​u​ ​a​r​e​ ​u​s​i​n​g​ ​D​e​s​k​t​o​p​,​ ​M​o​b​i​l​e​,​ ​C​l​o​u​d​,​ ​o​r​ ​s​e​l​f​-​h​o​s​t​e​d​ ​m​o​d​e​,​ ​a​n​d​ ​t​h​e​ ​e​x​a​c​t​ ​a​c​t​i​o​n​ ​t​h​a​t​ ​f​a​i​l​e​d​.
		 */
		includeBody: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Busabase
		 */
		appName: () => LocalizedString
	}
	shell: {
		/**
		 * Graph View
		 */
		graphView: () => LocalizedString
		/**
		 * Loading dashboard...
		 */
		loadingDashboard: () => LocalizedString
		/**
		 * Failed to load dashboard data
		 */
		failedToLoadDashboard: () => LocalizedString
		/**
		 * Couldn't move the item. Please try again.
		 */
		nodeMoveFailed: () => LocalizedString
		/**
		 * Dashboard route not found
		 */
		routeNotFoundTitle: () => LocalizedString
		/**
		 * Open Inbox, Activity, or a Base from the sidebar.
		 */
		routeNotFoundBody: () => LocalizedString
		/**
		 * Local Busabase
		 */
		localSpaceName: () => LocalizedString
		/**
		 * Local Reviewer
		 */
		localReviewerName: () => LocalizedString
		/**
		 * Local
		 */
		localPlan: () => LocalizedString
		/**
		 * Approval-first KB
		 */
		approvalFirstKb: () => LocalizedString
		/**
		 * Add workspace
		 */
		addWorkspace: () => LocalizedString
		/**
		 * Invite members
		 */
		inviteMembers: () => LocalizedString
		/**
		 * Account settings
		 */
		accountSettings: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Log out
		 */
		logOut: () => LocalizedString
		/**
		 * Notifications
		 */
		notifications: () => LocalizedString
		/**
		 * Workspaces
		 */
		workspaces: () => LocalizedString
		/**
		 * Auto
		 */
		auto: () => LocalizedString
	}
	navigation: {
		/**
		 * Review
		 */
		review: () => LocalizedString
		/**
		 * Inbox
		 */
		inbox: () => LocalizedString
		/**
		 * Activity
		 */
		activity: () => LocalizedString
		/**
		 * Base
		 */
		base: () => LocalizedString
		/**
		 * Blog Posts
		 */
		blogPosts: () => LocalizedString
	}
	vaultSettings: {
		/**
		 * Vault
		 */
		title: () => LocalizedString
		/**
		 * Store secrets and variables for agents, MCP servers, and API tools that call this Busabase instance.
		 */
		description: () => LocalizedString
		/**
		 * Vault
		 */
		openButton: () => LocalizedString
		/**
		 * Secrets
		 */
		secretsTab: () => LocalizedString
		/**
		 * Variables
		 */
		variablesTab: () => LocalizedString
		/**
		 * Name
		 */
		nameLabel: () => LocalizedString
		/**
		 * Value
		 */
		valueLabel: () => LocalizedString
		/**
		 * Value
		 */
		valuePlaceholder: () => LocalizedString
		/**
		 * Description
		 */
		descriptionLabel: () => LocalizedString
		/**
		 * Optional note
		 */
		descriptionPlaceholder: () => LocalizedString
		/**
		 * Add secret
		 */
		addSecret: () => LocalizedString
		/**
		 * Add variable
		 */
		addVariable: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Saving...
		 */
		saving: () => LocalizedString
		/**
		 * Loading vault items...
		 */
		loading: () => LocalizedString
		/**
		 * Failed to load vault items
		 */
		loadFailed: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Reveal
		 */
		reveal: () => LocalizedString
		/**
		 * Hide
		 */
		hide: () => LocalizedString
		/**
		 * Vault saved
		 */
		saved: () => LocalizedString
		/**
		 * Failed to save vault
		 */
		saveFailed: () => LocalizedString
		/**
		 * Vault cleared
		 */
		cleared: () => LocalizedString
		/**
		 * Local vault
		 */
		storageTitle: () => LocalizedString
		/**
		 * These items are stored in this local Busabase database. Secrets are encrypted when a vault encryption key is configured.
		 */
		storageDescription: () => LocalizedString
		/**
		 * Permissions
		 */
		accessTitle: () => LocalizedString
		/**
		 * Runtime access controls whether API, RPC, and MCP calls may use an item. Using a secret is separate from revealing it.
		 */
		accessDescription: () => LocalizedString
		/**
		 * Runtime access
		 */
		runtimeAccess: () => LocalizedString
		/**
		 * Sensitive
		 */
		secretsBadge: () => LocalizedString
		/**
		 * Non-sensitive
		 */
		variablesBadge: () => LocalizedString
		/**
		 * No secrets configured yet.
		 */
		noSecrets: () => LocalizedString
		/**
		 * No variables configured yet.
		 */
		noVariables: () => LocalizedString
	}
	webhookSettings: {
		/**
		 * Webhooks
		 */
		title: () => LocalizedString
		/**
		 * Automatically fire a webhook, notify an agent, or run a sandboxed function when something happens in this space.
		 */
		description: () => LocalizedString
		/**
		 * Webhooks
		 */
		openButton: () => LocalizedString
		/**
		 * Add rule
		 */
		addRule: () => LocalizedString
		/**
		 * Loading webhook rules...
		 */
		rulesLoading: () => LocalizedString
		/**
		 * Failed to load webhook rules
		 */
		rulesLoadFailed: () => LocalizedString
		/**
		 * No webhook rules configured yet.
		 */
		noRules: () => LocalizedString
		/**
		 * Name
		 */
		nameLabel: () => LocalizedString
		/**
		 * e.g. Notify Slack on new records
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Event
		 */
		eventTypeLabel: () => LocalizedString
		/**
		 * New Record
		 */
		eventTypeRecordCreated: () => LocalizedString
		/**
		 * @AI mention
		 */
		eventTypeAiMention: () => LocalizedString
		/**
		 * Changes requested
		 */
		eventTypeChangesRequested: () => LocalizedString
		/**
		 * Asset uploaded
		 */
		eventTypeAssetUploaded: () => LocalizedString
		/**
		 * Base
		 */
		baseScopeLabel: () => LocalizedString
		/**
		 * All bases
		 */
		baseScopeAll: () => LocalizedString
		/**
		 * Action
		 */
		actionKindLabel: () => LocalizedString
		/**
		 * Webhook
		 */
		actionKindWebhook: () => LocalizedString
		/**
		 * Notify agent
		 */
		actionKindNotifyAgent: () => LocalizedString
		/**
		 * Run function
		 */
		actionKindRunFunction: () => LocalizedString
		/**
		 * Target URL
		 */
		targetUrlLabel: () => LocalizedString
		/**
		 * https://example.com/hooks/busabase
		 */
		targetUrlPlaceholder: () => LocalizedString
		/**
		 * Secret
		 */
		secretLabel: () => LocalizedString
		/**
		 * Optional — used to sign the request
		 */
		secretPlaceholder: () => LocalizedString
		/**
		 * Leave blank to keep the current secret
		 */
		secretKeepPlaceholder: () => LocalizedString
		/**
		 * Secret configured
		 */
		secretConfigured: () => LocalizedString
		/**
		 * Code
		 */
		functionCodeLabel: () => LocalizedString
		/**
		 * // Inspect `input`, then call fetch(url, options) if needed
	return true;
		 */
		functionCodePlaceholder: () => LocalizedString
		/**
		 * The function receives `input` (the event payload) and can call `fetch(url, options)` to make outbound HTTP requests directly. Its return value is recorded for visibility only.
		 */
		functionHelperCaption: () => LocalizedString
		/**
		 * Timeout (ms)
		 */
		functionTimeoutLabel: () => LocalizedString
		/**
		 * Enabled
		 */
		enabledLabel: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Create rule
		 */
		createRule: () => LocalizedString
		/**
		 * Save changes
		 */
		saveChanges: () => LocalizedString
		/**
		 * Saving...
		 */
		saving: () => LocalizedString
		/**
		 * Webhook rule saved
		 */
		saved: () => LocalizedString
		/**
		 * Failed to save webhook rule
		 */
		saveFailed: () => LocalizedString
		/**
		 * Edit rule
		 */
		editRuleAction: () => LocalizedString
		/**
		 * Delete rule
		 */
		deleteRuleAction: () => LocalizedString
		/**
		 * Delete webhook rule
		 */
		deleteConfirmTitle: () => LocalizedString
		/**
		 * Delete the rule "{name}"? This cannot be undone.
		 */
		deleteConfirmBody: (arg: { name: string }) => LocalizedString
		/**
		 * Delete
		 */
		deleteConfirmAction: () => LocalizedString
		/**
		 * Failed to delete webhook rule
		 */
		deleteFailed: () => LocalizedString
		/**
		 * Test fired — success
		 */
		testFireSuccess: () => LocalizedString
		/**
		 * Test fired — failed, see log below
		 */
		testFireDeliveryFailed: () => LocalizedString
		/**
		 * Failed to test-fire webhook rule
		 */
		testFireRequestFailed: () => LocalizedString
		/**
		 * Success
		 */
		statusSuccess: () => LocalizedString
		/**
		 * Failed
		 */
		statusFailed: () => LocalizedString
		/**
		 * Skipped
		 */
		statusSkipped: () => LocalizedString
		/**
		 * Never run
		 */
		statusNeverRun: () => LocalizedString
		/**
		 * Test now
		 */
		testNowAction: () => LocalizedString
		/**
		 * View log
		 */
		viewLogAction: () => LocalizedString
		/**
		 * Hide log
		 */
		hideLogAction: () => LocalizedString
		/**
		 * Loading deliveries...
		 */
		deliveriesLoading: () => LocalizedString
		/**
		 * Failed to load deliveries
		 */
		deliveriesLoadFailed: () => LocalizedString
		/**
		 * No deliveries yet.
		 */
		noDeliveries: () => LocalizedString
	}
	marketing: {
		/**
		 * Open-source local review engine for Busabase.
		 */
		rootDescription: () => LocalizedString
		/**
		 * About BusaBase
		 */
		aboutTitle: () => LocalizedString
		/**
		 * BusaBase is an approval-first database for AI agents. Every AI-generated record must pass human review before it becomes canonical.
		 */
		aboutDescription: () => LocalizedString
		/**
		 * Why we built BusaBase
		 */
		aboutEyebrow: () => LocalizedString
		/**
		 * AI agents shouldn't exist to produce garbage at infinite speed
		 */
		aboutHeadline: () => LocalizedString
		/**
		 * An approval-first database for AI agents.
		 */
		aboutSubhead: () => LocalizedString
		/**
		 * Category:
		 */
		aboutCategory: () => LocalizedString
		/**
		 * (Approval | Privacy)-first (Database | Knowledgebase) for AI Agents
		 */
		aboutCategoryValue: () => LocalizedString
		/**
		 * Our conviction
		 */
		convictionTitle: () => LocalizedString
		/**
		 * The speed at which AI agents can generate content has outpaced the human capacity to evaluate it. The result: databases filled with unreviewed output, knowledge bases that nobody trusts, and teams drowning in AI-generated noise they can't act on.
		 */
		convictionP1: () => LocalizedString
		/**
		 * We built BusaBase because we believe AI agents should serve human interests — not optimize for throughput. Every piece of AI-generated content should earn its place in a knowledge base by passing human judgment first.
		 */
		convictionP2: () => LocalizedString
		/**
		 * That means: a change request comes in, a human reviews it, requests changes if needed, then approves. Only then does it become a canonical record. The audit trail stays forever. The team stays in control.
		 */
		convictionP3: () => LocalizedString
		/**
		 * What BusaBase is
		 */
		whatIsTitle: () => LocalizedString
		/**
		 * Approval-first
		 */
		pillarApprovalTitle: () => LocalizedString
		/**
		 * No AI output becomes a canonical record without human approval. Change Request → Review → Merge. Always.
		 */
		pillarApprovalBody: () => LocalizedString
		/**
		 * Privacy-first
		 */
		pillarPrivacyTitle: () => LocalizedString
		/**
		 * Open-source local engine. Your data never leaves your machine unless you choose to. No SaaS required.
		 */
		pillarPrivacyBody: () => LocalizedString
		/**
		 * Agent-native
		 */
		pillarAgentTitle: () => LocalizedString
		/**
		 * REST API and structured schema designed from the ground up for AI agent workflows, not retrofitted.
		 */
		pillarAgentBody: () => LocalizedString
		/**
		 * Open core
		 */
		openCoreTitle: () => LocalizedString
		/**
		 * BusaBase OSS (this app) is the open-source local engine — no login, one local workspace, PGLite persistence, REST APIs. It's the foundation: free forever, self-hostable, auditable.
		 */
		openCoreP1: () => LocalizedString
		/**
		 * BusaBase Cloud wraps the same core with multi-user workspaces, team roles, billing, and enterprise audit logs. It's the hosted layer for teams who want the approval workflow without running infrastructure.
		 */
		openCoreP2: () => LocalizedString
		/**
		 * Start reviewing AI output today
		 */
		aboutCtaTitle: () => LocalizedString
		/**
		 * Run the local engine, point your AI agent at the API, and let humans decide what becomes canonical.
		 */
		aboutCtaBody: () => LocalizedString
		/**
		 * Open Dashboard
		 */
		openDashboard: () => LocalizedString
		/**
		 * View on GitHub
		 */
		viewOnGithub: () => LocalizedString
		/**
		 * Download Busabase Desktop
		 */
		downloadTitle: () => LocalizedString
		/**
		 * Download Busabase Desktop for macOS, Windows, and Linux from the public Busabase desktop release channel.
		 */
		downloadDescription: () => LocalizedString
		/**
		 * Run Busabase as a local-first desktop app for approval-first AI agent data workflows.
		 */
		downloadOgDescription: () => LocalizedString
		/**
		 * Busabase API Documentation
		 */
		apiDocsTitle: () => LocalizedString
		/**
		 * Busabase Desktop
		 */
		desktopBadge: () => LocalizedString
		/**
		 * Download Busabase for your computer
		 */
		downloadHeadline: () => LocalizedString
		/**
		 * Run the approval-first local database for AI agents from a focused desktop app, with local storage, review queues, and updater-ready releases.
		 */
		downloadSubhead: () => LocalizedString
		/**
		 * Download latest version
		 */
		downloadLatest: () => LocalizedString
		/**
		 * Open web dashboard
		 */
		openWebDashboard: () => LocalizedString
		/**
		 * Latest desktop build
		 */
		latestDesktopBuild: () => LocalizedString
		/**
		 * Version {version}
		 */
		version: (arg: { version: string }) => LocalizedString
		/**
		 * Apple Silicon
		 */
		appleSilicon: () => LocalizedString
		/**
		 * Intel
		 */
		intel: () => LocalizedString
		/**
		 * Windows
		 */
		windows: () => LocalizedString
		/**
		 * Linux
		 */
		linux: () => LocalizedString
		/**
		 * For newer Macs with M-series chips.
		 */
		macAppleSiliconDescription: () => LocalizedString
		/**
		 * For Intel-based Macs.
		 */
		macIntelDescription: () => LocalizedString
		/**
		 * Choose the .msi or .exe bundle from the latest release.
		 */
		windowsDescription: () => LocalizedString
		/**
		 * Choose the .deb bundle from the latest release.
		 */
		linuxDescription: () => LocalizedString
		/**
		 * Mobile
		 */
		mobileTitle: () => LocalizedString
		/**
		 * Review queues and approvals on the go — get the Busabase app for iPhone, iPad, and Android.
		 */
		mobileBody: () => LocalizedString
		/**
		 * iPhone & iPad
		 */
		iphoneIpad: () => LocalizedString
		/**
		 * Phone & Tablet
		 */
		phoneTablet: () => LocalizedString
		/**
		 * Download on the App Store
		 */
		appStoreAction: () => LocalizedString
		/**
		 * Get it on Google Play
		 */
		googlePlayAction: () => LocalizedString
		/**
		 * Signing notice
		 */
		signingNoticeTitle: () => LocalizedString
		/**
		 * macOS and Windows bundles may show platform security warnings until code signing and notarization are fully configured.
		 */
		signingNoticeBody: () => LocalizedString
		/**
		 * Install flow
		 */
		installFlowTitle: () => LocalizedString
		/**
		 * Download the bundle for your operating system.
		 */
		installStep1: () => LocalizedString
		/**
		 * Open Busabase Desktop and start the local review engine.
		 */
		installStep2: () => LocalizedString
		/**
		 * Use the release channel for future desktop updates.
		 */
		installStep3: () => LocalizedString
	}
	support: {
		/**
		 * Busabase Support
		 */
		title: () => LocalizedString
		/**
		 * Get help with Busabase Desktop, Busabase Mobile, Agent Skill setup, and approval-first database workflows.
		 */
		description: () => LocalizedString
		/**
		 * Support
		 */
		badge: () => LocalizedString
		/**
		 * Get help with Busabase
		 */
		headline: () => LocalizedString
		/**
		 * Use these support paths for Busabase Desktop, Busabase Mobile, local review workflows, and AI agent setup.
		 */
		subhead: () => LocalizedString
		/**
		 * Email support
		 */
		emailTitle: () => LocalizedString
		/**
		 * Send your workspace, device, and a short description of what went wrong. Include screenshots or logs when possible.
		 */
		emailBody: () => LocalizedString
		/**
		 * Set up Agent Skill
		 */
		setupTitle: () => LocalizedString
		/**
		 * Connect Claude Code, Codex, or another AI agent to Busabase so it can create reviewed change requests.
		 */
		setupBody: () => LocalizedString
		/**
		 * Open setup guide
		 */
		setupAction: () => LocalizedString
		/**
		 * Download apps
		 */
		downloadTitle: () => LocalizedString
		/**
		 * Install the desktop app for the local review engine, or use the mobile app to review changes on the go.
		 */
		downloadBody: () => LocalizedString
		/**
		 * Open downloads
		 */
		downloadAction: () => LocalizedString
		/**
		 * Open dashboard
		 */
		dashboardTitle: () => LocalizedString
		/**
		 * Check the local inbox, activity feed, base schema, and pending change requests in your Busabase workspace.
		 */
		dashboardBody: () => LocalizedString
		/**
		 * Open dashboard
		 */
		dashboardAction: () => LocalizedString
		/**
		 * What to include
		 */
		includeTitle: () => LocalizedString
		/**
		 * For faster troubleshooting, include your Busabase version, operating system, whether you are using Desktop, Mobile, Cloud, or self-hosted mode, and the exact action that failed.
		 */
		includeBody: () => LocalizedString
	}
}

export type Formatters = {}
