import type {
  SeedBaseDef,
  SeedFieldDef,
  SeedRecordDef,
  SeedScenario,
  SeedViewDef,
} from "../seed-types";

// This base lives under the existing Marketing folder (DEMO_CONTENT_FOLDER_NODE_ID
// in dataset.ts). Hardcoded here to avoid a circular import back into dataset.ts.
const MARKETING_FOLDER_NODE_ID = "nod_content";

export const DEMO_DIRECTORY_LISTINGS_BASE_ID = "bse_local_directory_listings";
export const DEMO_DIRECTORY_LISTINGS_BASE_NODE_ID = "nod_base_directory_listings";

// Shared field shape (same slugs/ids/choice-ids as the zh-cn twin — only labels differ).
const directoryFields: SeedFieldDef[] = [
  {
    id: "bsf_dir_directory",
    slug: "directory",
    name: "Directory",
    type: "text",
    required: true,
    options: {},
  },
  {
    id: "bsf_dir_homepage",
    slug: "homepage_url",
    name: "Homepage URL",
    type: "url",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_category",
    slug: "category",
    name: "Category",
    type: "select",
    required: false,
    options: {
      choices: [
        { id: "launch", name: "Launch platform", color: "violet" },
        { id: "review", name: "Review site", color: "amber" },
        { id: "ai-directory", name: "AI directory", color: "cyan" },
        { id: "startup", name: "Startup directory", color: "emerald" },
        { id: "app-store", name: "App store", color: "rose" },
      ],
    },
  },
  {
    id: "bsf_dir_status",
    slug: "status",
    name: "Status",
    type: "select",
    required: false,
    options: {
      choices: [
        { id: "planned", name: "Planned", color: "slate" },
        { id: "submitted", name: "Submitted", color: "amber" },
        { id: "live", name: "Live", color: "emerald" },
        { id: "rejected", name: "Rejected", color: "rose" },
        { id: "needs-update", name: "Needs update", color: "orange" },
      ],
    },
  },
  {
    id: "bsf_dir_listing",
    slug: "listing_url",
    name: "Listing URL",
    type: "url",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_dr",
    slug: "domain_rating",
    name: "Domain Rating",
    type: "number",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_traffic",
    slug: "monthly_traffic",
    name: "Monthly Traffic",
    type: "number",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_dofollow",
    slug: "dofollow",
    name: "Do-follow",
    type: "checkbox",
    required: false,
    options: {},
  },
  { id: "bsf_dir_cost", slug: "cost", name: "Cost", type: "text", required: false, options: {} },
  {
    id: "bsf_dir_submitted",
    slug: "submitted",
    name: "Submitted",
    type: "date",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_priority",
    slug: "priority",
    name: "Priority",
    type: "select",
    required: false,
    options: {
      choices: [
        { id: "high", name: "High", color: "rose" },
        { id: "medium", name: "Medium", color: "amber" },
        { id: "low", name: "Low", color: "slate" },
      ],
    },
  },
  {
    id: "bsf_dir_owner",
    slug: "owner",
    name: "Owner",
    type: "email",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_notes",
    slug: "notes",
    name: "Notes",
    type: "longtext",
    required: false,
    options: {},
  },
];

export const DIRECTORY_LISTINGS_BASES: SeedBaseDef[] = [
  {
    id: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    nodeId: DEMO_DIRECTORY_LISTINGS_BASE_NODE_ID,
    slug: "directory-listings",
    name: "Directory Listings",
    description:
      "Where we've listed the product — launch platforms, review sites, and AI directories — tracked with status and SEO value (domain rating, traffic, do-follow). Like a backlink / submission tracker.",
    folderNodeId: MARKETING_FOLDER_NODE_ID,
    useCases: ["directories"],
    fields: directoryFields,
  },
];

type DirRow = { key: string; minutesAgo: number; fields: Record<string, unknown> };

const rows: DirRow[] = [
  {
    key: "product_hunt",
    minutesAgo: 90,
    fields: {
      directory: "Product Hunt",
      homepage_url: "https://www.producthunt.com",
      category: "launch",
      status: "live",
      listing_url: "https://www.producthunt.com/products/busabase",
      domain_rating: 91,
      monthly_traffic: 6500000,
      dofollow: true,
      cost: "Free",
      submitted: "2026-05-12",
      priority: "high",
      owner: "growth@busabase.local",
      notes: "Launched on a Tuesday — #3 Product of the Day. Drove the first ~400 signups.",
    },
  },
  {
    key: "hacker_news",
    minutesAgo: 130,
    fields: {
      directory: "Hacker News (Show HN)",
      homepage_url: "https://news.ycombinator.com",
      category: "launch",
      status: "live",
      listing_url: "https://news.ycombinator.com/item?id=demo",
      domain_rating: 92,
      monthly_traffic: 12000000,
      dofollow: true,
      cost: "Free",
      submitted: "2026-05-13",
      priority: "high",
      owner: "growth@busabase.local",
      notes: "Show HN front-paged for ~5 hours. Strong dev signal, lots of GitHub stars.",
    },
  },
  {
    key: "g2",
    minutesAgo: 220,
    fields: {
      directory: "G2",
      homepage_url: "https://www.g2.com",
      category: "review",
      status: "submitted",
      domain_rating: 90,
      monthly_traffic: 9000000,
      dofollow: false,
      cost: "Free profile, paid tiers",
      submitted: "2026-05-28",
      priority: "high",
      owner: "seo@busabase.local",
      notes: "Profile claimed; collecting the first 10 reviews to unlock a category badge.",
    },
  },
  {
    key: "capterra",
    minutesAgo: 400,
    fields: {
      directory: "Capterra",
      homepage_url: "https://www.capterra.com",
      category: "review",
      status: "planned",
      domain_rating: 88,
      monthly_traffic: 7000000,
      dofollow: false,
      cost: "PPC / paid",
      priority: "medium",
      owner: "seo@busabase.local",
      notes: "Gartner network. Hold until we have budget for the PPC model.",
    },
  },
  {
    key: "alternativeto",
    minutesAgo: 300,
    fields: {
      directory: "AlternativeTo",
      homepage_url: "https://alternativeto.net",
      category: "review",
      status: "live",
      listing_url: "https://alternativeto.net/software/busabase",
      domain_rating: 80,
      monthly_traffic: 5500000,
      dofollow: true,
      cost: "Free",
      submitted: "2026-05-18",
      priority: "high",
      owner: "seo@busabase.local",
      notes: "Listed as an alternative to Airtable/Notion. Good long-tail SEO referral.",
    },
  },
  {
    key: "betalist",
    minutesAgo: 520,
    fields: {
      directory: "BetaList",
      homepage_url: "https://betalist.com",
      category: "startup",
      status: "live",
      listing_url: "https://betalist.com/startups/busabase",
      domain_rating: 72,
      monthly_traffic: 600000,
      dofollow: true,
      cost: "Free (or paid skip-the-queue)",
      submitted: "2026-05-09",
      priority: "medium",
      owner: "growth@busabase.local",
      notes: "Early-adopter audience; collected ~120 waitlist emails pre-launch.",
    },
  },
  {
    key: "theres_an_ai",
    minutesAgo: 180,
    fields: {
      directory: "There's An AI For That",
      homepage_url: "https://theresanaiforthat.com",
      category: "ai-directory",
      status: "live",
      listing_url: "https://theresanaiforthat.com/ai/busabase",
      domain_rating: 75,
      monthly_traffic: 3500000,
      dofollow: true,
      cost: "Free, paid featured",
      submitted: "2026-05-20",
      priority: "high",
      owner: "growth@busabase.local",
      notes: "Largest AI tools directory. Submitted under 'AI database / agent data'.",
    },
  },
  {
    key: "futurepedia",
    minutesAgo: 260,
    fields: {
      directory: "Futurepedia",
      homepage_url: "https://www.futurepedia.io",
      category: "ai-directory",
      status: "submitted",
      domain_rating: 71,
      monthly_traffic: 2000000,
      dofollow: true,
      cost: "Free, $99 featured",
      submitted: "2026-05-29",
      priority: "medium",
      owner: "growth@busabase.local",
      notes: "Awaiting review (~1 week queue). Considering the featured slot for launch week.",
    },
  },
  {
    key: "saashub",
    minutesAgo: 700,
    fields: {
      directory: "SaaSHub",
      homepage_url: "https://www.saashub.com",
      category: "review",
      status: "live",
      listing_url: "https://www.saashub.com/busabase",
      domain_rating: 64,
      monthly_traffic: 800000,
      dofollow: true,
      cost: "Free",
      submitted: "2026-05-22",
      priority: "low",
      owner: "seo@busabase.local",
      notes: "Do-follow backlink. Low traffic but easy, indexed quickly.",
    },
  },
  {
    key: "getapp",
    minutesAgo: 900,
    fields: {
      directory: "GetApp",
      homepage_url: "https://www.getapp.com",
      category: "review",
      status: "planned",
      domain_rating: 80,
      monthly_traffic: 3000000,
      dofollow: false,
      cost: "PPC / paid",
      priority: "low",
      owner: "seo@busabase.local",
      notes: "Gartner network (same as Capterra). Bundle the submission with Capterra.",
    },
  },
  {
    key: "stackshare",
    minutesAgo: 1100,
    fields: {
      directory: "StackShare",
      homepage_url: "https://stackshare.io",
      category: "startup",
      status: "needs-update",
      listing_url: "https://stackshare.io/busabase",
      domain_rating: 78,
      monthly_traffic: 1200000,
      dofollow: true,
      cost: "Free",
      submitted: "2026-04-30",
      priority: "low",
      owner: "growth@busabase.local",
      notes: "Listing is live but logo + description are stale — refresh after the rebrand.",
    },
  },
  {
    key: "indiehackers",
    minutesAgo: 1400,
    fields: {
      directory: "IndieHackers",
      homepage_url: "https://www.indiehackers.com",
      category: "startup",
      status: "live",
      listing_url: "https://www.indiehackers.com/product/busabase",
      domain_rating: 78,
      monthly_traffic: 1500000,
      dofollow: true,
      cost: "Free",
      submitted: "2026-05-06",
      priority: "medium",
      owner: "growth@busabase.local",
      notes: "Posted the build-in-public milestone thread; good founder-audience engagement.",
    },
  },
];

export const DIRECTORY_LISTINGS_RECORDS: SeedRecordDef[] = rows.map((r) => ({
  id: `rec_seed_dir_${r.key}`,
  baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
  commitId: `cmt_seed_dir_${r.key}`,
  fields: r.fields,
  message: `Seed directory listing — ${r.fields.directory}`,
  author: "seed-growth",
  // Older than the core seed records so they don't displace them in the recent page.
  minutesAgo: r.minutesAgo + 5000,
  useCases: ["directories"],
}));

export const DIRECTORY_LISTINGS_VIEWS: SeedViewDef[] = [
  {
    id: "viw_seed_dir_by_status",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "by-status",
    name: "By status",
    description: "Every directory, sorted by submission status.",
    config: { filters: [], sorts: [{ fieldSlug: "status", direction: "asc" }] },
    minutesAgo: 60,
    useCases: ["directories"],
  },
  {
    id: "viw_seed_dir_live_dofollow",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "live-dofollow",
    name: "Live · do-follow",
    description: "Live listings that pass a do-follow backlink — the real SEO value.",
    config: {
      filters: [
        { fieldSlug: "status", operator: "equals", value: "live" },
        { fieldSlug: "dofollow", operator: "is_true" },
      ],
      sorts: [{ fieldSlug: "domain_rating", direction: "desc" }],
    },
    minutesAgo: 59,
    useCases: ["directories"],
  },
  {
    id: "viw_seed_dir_planned_high",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "planned-high-priority",
    name: "Planned · high priority",
    description: "High-priority directories we still need to submit to.",
    config: {
      filters: [
        { fieldSlug: "status", operator: "equals", value: "planned" },
        { fieldSlug: "priority", operator: "equals", value: "high" },
      ],
      sorts: [{ fieldSlug: "domain_rating", direction: "desc" }],
    },
    minutesAgo: 58,
    useCases: ["directories"],
  },
];

export const directoryListingScenario: SeedScenario = {
  bases: DIRECTORY_LISTINGS_BASES,
  records: DIRECTORY_LISTINGS_RECORDS,
  views: DIRECTORY_LISTINGS_VIEWS,
};
