import type {
  SeedBaseDef,
  SeedFieldDef,
  SeedRecordDef,
  SeedScenario,
  SeedViewDef,
} from "../seed-types";
import {
  DEMO_DIRECTORY_LISTINGS_BASE_ID,
  DEMO_DIRECTORY_LISTINGS_BASE_NODE_ID,
} from "./directory-listing";

// 与英文版同一个「内容管理」文件夹(DEMO_CONTENT_FOLDER_NODE_ID),挂在其下。
const CONTENT_FOLDER_NODE_ID = "nod_content";

// 字段 slug / 选项 id 与英文版保持一致,仅展示名称为中文。
const directoryFields: SeedFieldDef[] = [
  {
    id: "bsf_dir_directory",
    slug: "directory",
    name: "渠道 / 目录",
    type: "text",
    required: true,
    options: {},
  },
  {
    id: "bsf_dir_homepage",
    slug: "homepage_url",
    name: "官网链接",
    type: "url",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_category",
    slug: "category",
    name: "类型",
    type: "select",
    required: false,
    options: {
      choices: [
        { id: "launch", name: "发布平台", color: "violet" },
        { id: "review", name: "评测 / 媒体", color: "amber" },
        { id: "ai-directory", name: "AI 工具目录", color: "cyan" },
        { id: "startup", name: "创业 / 社区", color: "emerald" },
        { id: "app-store", name: "应用市场", color: "rose" },
      ],
    },
  },
  {
    id: "bsf_dir_status",
    slug: "status",
    name: "状态",
    type: "select",
    required: false,
    options: {
      choices: [
        { id: "planned", name: "计划中", color: "slate" },
        { id: "submitted", name: "已提交", color: "amber" },
        { id: "live", name: "已上线", color: "emerald" },
        { id: "rejected", name: "被拒", color: "rose" },
        { id: "needs-update", name: "待更新", color: "orange" },
      ],
    },
  },
  {
    id: "bsf_dir_listing",
    slug: "listing_url",
    name: "上架链接",
    type: "url",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_dr",
    slug: "domain_rating",
    name: "域名权重(DR)",
    type: "number",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_traffic",
    slug: "monthly_traffic",
    name: "月访问量",
    type: "number",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_dofollow",
    slug: "dofollow",
    name: "Dofollow 外链",
    type: "checkbox",
    required: false,
    options: {},
  },
  { id: "bsf_dir_cost", slug: "cost", name: "费用", type: "text", required: false, options: {} },
  {
    id: "bsf_dir_submitted",
    slug: "submitted",
    name: "提交日期",
    type: "date",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_priority",
    slug: "priority",
    name: "优先级",
    type: "select",
    required: false,
    options: {
      choices: [
        { id: "high", name: "高", color: "rose" },
        { id: "medium", name: "中", color: "amber" },
        { id: "low", name: "低", color: "slate" },
      ],
    },
  },
  {
    id: "bsf_dir_owner",
    slug: "owner",
    name: "负责人",
    type: "email",
    required: false,
    options: {},
  },
  {
    id: "bsf_dir_notes",
    slug: "notes",
    name: "备注",
    type: "longtext",
    required: false,
    options: {},
  },
];

const directoryBases: SeedBaseDef[] = [
  {
    id: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    nodeId: DEMO_DIRECTORY_LISTINGS_BASE_NODE_ID,
    slug: "directory-listings",
    name: "渠道投放清单",
    description:
      "产品在各发布平台、评测媒体、AI 工具目录的上架情况——记录状态与 SEO 价值(域名权重、流量、是否 dofollow),类似外链 / 投放追踪表。",
    folderNodeId: CONTENT_FOLDER_NODE_ID,
    useCases: ["directories"],
    fields: directoryFields,
  },
];

type DirRow = { key: string; minutesAgo: number; fields: Record<string, unknown> };

const rows: DirRow[] = [
  {
    key: "product_hunt",
    minutesAgo: 90,
    fields: {
      directory: "Product Hunt(产品猎人)",
      homepage_url: "https://www.producthunt.com",
      category: "launch",
      status: "live",
      listing_url: "https://www.producthunt.com/products/busabase",
      domain_rating: 91,
      monthly_traffic: 6500000,
      dofollow: true,
      cost: "免费",
      submitted: "2026-05-12",
      priority: "high",
      owner: "growth@busabase.local",
      notes: "周二发布,当日 #3。出海冷启动首选,带来前 ~400 注册。",
    },
  },
  {
    key: "sspai",
    minutesAgo: 150,
    fields: {
      directory: "少数派",
      homepage_url: "https://sspai.com",
      category: "review",
      status: "live",
      listing_url: "https://sspai.com/post/demo",
      domain_rating: 78,
      monthly_traffic: 4000000,
      dofollow: true,
      cost: "免费投稿",
      submitted: "2026-05-16",
      priority: "high",
      owner: "growth@busabase.local",
      notes: "投了一篇效率工具测评,过稿后首页推荐,转化质量高。",
    },
  },
  {
    key: "kr36",
    minutesAgo: 240,
    fields: {
      directory: "36氪",
      homepage_url: "https://36kr.com",
      category: "review",
      status: "submitted",
      domain_rating: 82,
      monthly_traffic: 15000000,
      dofollow: false,
      cost: "免费 / 付费 PR",
      submitted: "2026-05-27",
      priority: "medium",
      owner: "pr@busabase.local",
      notes: "投了融资 / 产品稿,等编辑回复。自然外链多为 nofollow。",
    },
  },
  {
    key: "jike",
    minutesAgo: 320,
    fields: {
      directory: "即刻",
      homepage_url: "https://okjike.com",
      category: "startup",
      status: "live",
      domain_rating: 60,
      monthly_traffic: 3000000,
      dofollow: false,
      cost: "免费",
      submitted: "2026-05-10",
      priority: "medium",
      owner: "growth@busabase.local",
      notes: "在「一起做产品」圈子做 build-in-public,互动不错,适合早期种子用户。",
    },
  },
  {
    key: "v2ex",
    minutesAgo: 420,
    fields: {
      directory: "V2EX",
      homepage_url: "https://www.v2ex.com",
      category: "startup",
      status: "live",
      listing_url: "https://www.v2ex.com/t/demo",
      domain_rating: 74,
      monthly_traffic: 5000000,
      dofollow: true,
      cost: "免费",
      submitted: "2026-05-11",
      priority: "high",
      owner: "growth@busabase.local",
      notes: "发在「分享创造」节点,开发者群体精准,带来一批技术用户。",
    },
  },
  {
    key: "juejin",
    minutesAgo: 560,
    fields: {
      directory: "掘金",
      homepage_url: "https://juejin.cn",
      category: "review",
      status: "live",
      domain_rating: 76,
      monthly_traffic: 8000000,
      dofollow: false,
      cost: "免费",
      submitted: "2026-05-14",
      priority: "medium",
      owner: "growth@busabase.local",
      notes: "发了一篇技术实践文,沉淀长尾搜索流量。",
    },
  },
  {
    key: "appinn",
    minutesAgo: 700,
    fields: {
      directory: "小众软件",
      homepage_url: "https://www.appinn.com",
      category: "review",
      status: "submitted",
      domain_rating: 70,
      monthly_traffic: 1500000,
      dofollow: true,
      cost: "免费推荐",
      submitted: "2026-05-26",
      priority: "low",
      owner: "growth@busabase.local",
      notes: "提交了软件推荐,等收录。dofollow 外链,利于收录。",
    },
  },
  {
    key: "ai_gongjuji",
    minutesAgo: 200,
    fields: {
      directory: "AI 工具集",
      homepage_url: "https://ai-bot.cn",
      category: "ai-directory",
      status: "live",
      listing_url: "https://ai-bot.cn/busabase",
      domain_rating: 66,
      monthly_traffic: 2500000,
      dofollow: true,
      cost: "免费 / 付费收录",
      submitted: "2026-05-19",
      priority: "high",
      owner: "growth@busabase.local",
      notes: "国内最大的 AI 工具导航之一,收录在「AI 数据库 / 效率」分类。",
    },
  },
  {
    key: "toolify",
    minutesAgo: 280,
    fields: {
      directory: "Toolify.ai",
      homepage_url: "https://www.toolify.ai",
      category: "ai-directory",
      status: "submitted",
      domain_rating: 72,
      monthly_traffic: 2000000,
      dofollow: true,
      cost: "免费 / 付费 featured",
      submitted: "2026-05-29",
      priority: "medium",
      owner: "growth@busabase.local",
      notes: "出海 AI 导航,中英双语流量。已提交,等审核。",
    },
  },
  {
    key: "ifanr",
    minutesAgo: 1000,
    fields: {
      directory: "爱范儿 / MindStore",
      homepage_url: "https://www.ifanr.com",
      category: "review",
      status: "planned",
      domain_rating: 80,
      monthly_traffic: 6000000,
      dofollow: false,
      cost: "免费 / 付费 PR",
      priority: "low",
      owner: "pr@busabase.local",
      notes: "计划投 MindStore 产品栏目,等产品打磨到更适合大众媒体再投。",
    },
  },
  {
    key: "ruanyf",
    minutesAgo: 1200,
    fields: {
      directory: "科技爱好者周刊(阮一峰)",
      homepage_url: "https://www.ruanyifeng.com/blog",
      category: "launch",
      status: "needs-update",
      domain_rating: 79,
      monthly_traffic: 4000000,
      dofollow: true,
      cost: "免费投稿",
      submitted: "2026-04-28",
      priority: "low",
      owner: "growth@busabase.local",
      notes: "被收录在工具推荐里,但介绍是旧版,改版后需要去 GitHub issue 更新。",
    },
  },
  {
    key: "zhihu",
    minutesAgo: 1500,
    fields: {
      directory: "知乎",
      homepage_url: "https://www.zhihu.com",
      category: "startup",
      status: "live",
      domain_rating: 88,
      monthly_traffic: 30000000,
      dofollow: false,
      cost: "免费",
      submitted: "2026-05-08",
      priority: "medium",
      owner: "growth@busabase.local",
      notes: "在「有哪些好用的数据库 / 表格工具」问题下做了回答,长尾搜索稳定带量。",
    },
  },
];

const directoryRecords: SeedRecordDef[] = rows.map((r) => ({
  id: `rec_seed_dir_zh_${r.key}`,
  baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
  commitId: `cmt_seed_dir_zh_${r.key}`,
  fields: r.fields,
  message: `录入渠道投放 — ${r.fields.directory}`,
  author: "seed-growth",
  // 比核心种子记录更旧,避免挤占最近记录页。
  minutesAgo: r.minutesAgo + 5000,
  useCases: ["directories"],
}));

const directoryViews: SeedViewDef[] = [
  {
    id: "viw_seed_dir_zh_by_status",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "by-status",
    name: "按状态",
    description: "所有渠道,按提交状态排序。",
    config: { filters: [], sorts: [{ fieldSlug: "status", direction: "asc" }] },
    minutesAgo: 60,
    useCases: ["directories"],
  },
  {
    id: "viw_seed_dir_zh_live_dofollow",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "live-dofollow",
    name: "已上线 · dofollow",
    description: "已上线且带 dofollow 外链的渠道——真正的 SEO 价值。",
    config: {
      filters: [
        { fieldSlug: "status", operator: "equals", value: "live" },
        { fieldSlug: "dofollow", operator: "is_true" },
      ],
      sorts: [{ fieldSlug: "domain_rating", direction: "desc" }],
    },
    minutesAgo: 59,
    useCases: ["directories"],
  },
  {
    id: "viw_seed_dir_zh_planned_high",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "planned-high-priority",
    name: "计划中 · 高优先级",
    description: "还没投、但优先级高的渠道。",
    config: {
      filters: [
        { fieldSlug: "status", operator: "equals", value: "planned" },
        { fieldSlug: "priority", operator: "equals", value: "high" },
      ],
      sorts: [{ fieldSlug: "domain_rating", direction: "desc" }],
    },
    minutesAgo: 58,
    useCases: ["directories"],
  },
  {
    id: "viw_seed_dir_zh_board",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "board",
    name: "投放看板",
    description: "所有渠道按状态分列 —— 拖动卡片即可推进。",
    type: "kanban",
    config: { filters: [], sorts: [], stackByFieldSlug: "status" },
    minutesAgo: 57,
    useCases: ["directories"],
  },
  {
    id: "viw_seed_dir_zh_calendar",
    baseId: DEMO_DIRECTORY_LISTINGS_BASE_ID,
    slug: "calendar",
    name: "投放日历",
    description: "按提交月份把渠道排到日历上。",
    type: "calendar",
    config: { filters: [], sorts: [], dateFieldSlug: "submitted" },
    minutesAgo: 56,
    useCases: ["directories"],
  },
];

export const directoryListingZhCnScenario: SeedScenario = {
  bases: directoryBases,
  records: directoryRecords,
  views: directoryViews,
};
