import type { SeedScenario } from "../seed-types";

/**
 * 扩展中文 demo 数据 — 确保每个文件夹至少 3 个数据表，页面数据充足。
 *
 * 覆盖的文件夹 (folder node ID → 新增 base):
 *   财务管理 (nod_finance)         → 费用报销
 *   知识管理 (nod_knowledge)       → 会议纪要、项目文档
 *   运营管理 (nod_operations)      → 活动策划、渠道管理
 *   日常任务 (nod_routine)         → 待办事项、周报记录
 *   合规审查 (nod_compliance)      → 风险登记册、合同台账
 *   市场研究 (nod_research)        → 竞品分析、用户访谈
 *   内容工厂 (nod_content_factory) → 选题库、编辑日历
 *   数据集库 (nod_datasets)        → 模型评估记录
 */
export const expandZhCnScenario: SeedScenario = {
  bases: [
    // ── 财务管理 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_expense",
      nodeId: "nod_zh_base_expense",
      folderNodeId: "nod_finance",
      slug: "expense-reimbursements",
      name: "费用报销",
      description: "员工费用申请与审批记录，关联发票与报销单。",
      useCases: ["finance"],
      fields: [
        {
          id: "bsf_zh_exp_title",
          slug: "title",
          name: "标题",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_exp_amount",
          slug: "amount",
          name: "金额（元）",
          type: "number",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_exp_category",
          slug: "category",
          name: "类别",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "travel", name: "差旅", color: "blue" },
              { id: "meal", name: "餐饮", color: "amber" },
              { id: "office", name: "办公用品", color: "emerald" },
              { id: "equipment", name: "设备", color: "violet" },
              { id: "other", name: "其他", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_exp_applicant",
          slug: "applicant",
          name: "申请人",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_exp_date",
          slug: "apply_date",
          name: "申请日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_exp_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "pending", name: "待审核", color: "amber" },
              { id: "approved", name: "已批准", color: "emerald" },
              { id: "rejected", name: "已拒绝", color: "rose" },
              { id: "reimbursed", name: "已报销", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_exp_notes",
          slug: "notes",
          name: "备注",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_exp_contract_ref",
          slug: "contract-ref",
          name: "关联合同",
          type: "relation",
          required: false,
          options: { targetBaseId: "bse_zh_contracts" },
        },
      ],
    },

    // ── 知识管理 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_meeting",
      nodeId: "nod_zh_base_meeting",
      folderNodeId: "nod_knowledge",
      slug: "meeting-notes",
      name: "会议纪要",
      description: "各类会议记录，包含议程、结论与跟进事项。",
      useCases: ["knowledge"],
      fields: [
        {
          id: "bsf_zh_mtg_title",
          slug: "title",
          name: "主题",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_mtg_date",
          slug: "date",
          name: "日期",
          type: "date",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_mtg_attendees",
          slug: "attendees",
          name: "参会人员",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_mtg_summary",
          slug: "summary",
          name: "会议摘要",
          type: "markdown",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_mtg_actions",
          slug: "action_items",
          name: "跟进事项",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_mtg_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "draft", name: "草稿", color: "amber" },
              { id: "confirmed", name: "已确认", color: "emerald" },
            ],
          },
        },
        {
          id: "bsf_zh_mtg_todos_ref",
          slug: "action-items-ref",
          name: "关联待办",
          type: "relation",
          required: false,
          options: { targetBaseId: "bse_zh_todos" },
        },
      ],
    },
    {
      id: "bse_zh_projdoc",
      nodeId: "nod_zh_base_projdoc",
      folderNodeId: "nod_knowledge",
      slug: "project-docs",
      name: "项目文档",
      description: "项目需求、设计规范、技术报告及里程碑记录。",
      useCases: ["knowledge"],
      fields: [
        {
          id: "bsf_zh_pd_title",
          slug: "title",
          name: "文档标题",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_pd_project",
          slug: "project",
          name: "所属项目",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_pd_type",
          slug: "type",
          name: "类型",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "spec", name: "需求规格", color: "blue" },
              { id: "design", name: "设计方案", color: "violet" },
              { id: "report", name: "技术报告", color: "emerald" },
              { id: "standard", name: "规范标准", color: "amber" },
            ],
          },
        },
        {
          id: "bsf_zh_pd_version",
          slug: "version",
          name: "版本",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_pd_content",
          slug: "content",
          name: "内容",
          type: "markdown",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_pd_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "draft", name: "草稿", color: "amber" },
              { id: "review", name: "评审中", color: "blue" },
              { id: "published", name: "已发布", color: "emerald" },
            ],
          },
        },
        {
          id: "bsf_zh_pd_meeting_ref",
          slug: "meeting-ref",
          name: "关联会议",
          type: "relation",
          required: false,
          options: { targetBaseId: "bse_zh_meeting" },
        },
      ],
    },

    // ── 运营管理 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_events",
      nodeId: "nod_zh_base_events",
      folderNodeId: "nod_operations",
      slug: "event-planning",
      name: "活动策划",
      description: "线上线下活动的策划、预算与执行跟踪。",
      useCases: ["operations"],
      fields: [
        {
          id: "bsf_zh_ev_name",
          slug: "name",
          name: "活动名称",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ev_type",
          slug: "type",
          name: "形式",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "online", name: "线上", color: "blue" },
              { id: "offline", name: "线下", color: "emerald" },
              { id: "hybrid", name: "混合", color: "violet" },
            ],
          },
        },
        {
          id: "bsf_zh_ev_date",
          slug: "event_date",
          name: "活动日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ev_budget",
          slug: "budget",
          name: "预算（元）",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ev_owner",
          slug: "owner",
          name: "负责人",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ev_desc",
          slug: "description",
          name: "活动简介",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ev_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "planning", name: "计划中", color: "amber" },
              { id: "ongoing", name: "进行中", color: "blue" },
              { id: "done", name: "已完成", color: "emerald" },
              { id: "cancelled", name: "已取消", color: "rose" },
            ],
          },
        },
        {
          id: "bsf_zh_ev_channel_ref",
          slug: "channel-ref",
          name: "关联渠道",
          type: "relation",
          required: false,
          options: { targetBaseId: "bse_zh_channels" },
        },
      ],
    },
    {
      id: "bse_zh_channels",
      nodeId: "nod_zh_base_channels",
      folderNodeId: "nod_operations",
      slug: "channel-management",
      name: "渠道管理",
      description: "各营销与销售渠道的运营状态、负责人及月度目标。",
      useCases: ["operations"],
      fields: [
        {
          id: "bsf_zh_ch_name",
          slug: "name",
          name: "渠道名称",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ch_platform",
          slug: "platform",
          name: "平台",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "wechat", name: "微信", color: "emerald" },
              { id: "douyin", name: "抖音", color: "slate" },
              { id: "weibo", name: "微博", color: "rose" },
              { id: "linkedin", name: "LinkedIn", color: "blue" },
              { id: "website", name: "官网", color: "violet" },
              { id: "other", name: "其他", color: "amber" },
            ],
          },
        },
        {
          id: "bsf_zh_ch_owner",
          slug: "owner",
          name: "负责人",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ch_goal",
          slug: "monthly_goal",
          name: "月度目标",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ch_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "active", name: "活跃", color: "emerald" },
              { id: "paused", name: "暂停", color: "amber" },
              { id: "inactive", name: "停用", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_ch_notes",
          slug: "notes",
          name: "运营备注",
          type: "text",
          required: false,
          options: {},
        },
      ],
    },

    // ── 日常任务 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_todos",
      nodeId: "nod_zh_base_todos",
      folderNodeId: "nod_routine",
      slug: "todos",
      name: "待办事项",
      description: "个人与团队待办任务，支持优先级排序与截止日期追踪。",
      useCases: ["routine"],
      fields: [
        {
          id: "bsf_zh_td_title",
          slug: "title",
          name: "任务标题",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_td_priority",
          slug: "priority",
          name: "优先级",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "high", name: "高", color: "rose" },
              { id: "medium", name: "中", color: "amber" },
              { id: "low", name: "低", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_td_due",
          slug: "due_date",
          name: "截止日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_td_assignee",
          slug: "assignee",
          name: "负责人",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_td_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "open", name: "待处理", color: "amber" },
              { id: "in_progress", name: "进行中", color: "blue" },
              { id: "done", name: "已完成", color: "emerald" },
              { id: "blocked", name: "已搁置", color: "rose" },
            ],
          },
        },
        {
          id: "bsf_zh_td_desc",
          slug: "description",
          name: "任务描述",
          type: "text",
          required: false,
          options: {},
        },
      ],
    },
    {
      id: "bse_zh_weekly",
      nodeId: "nod_zh_base_weekly",
      folderNodeId: "nod_routine",
      slug: "weekly-reports",
      name: "周报记录",
      description: "团队周报归档，记录本周亮点、阻碍与下周计划。",
      useCases: ["routine"],
      fields: [
        {
          id: "bsf_zh_wr_period",
          slug: "period",
          name: "周期",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_wr_highlights",
          slug: "highlights",
          name: "本周亮点",
          type: "markdown",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_wr_blockers",
          slug: "blockers",
          name: "遇到的阻碍",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_wr_next",
          slug: "next_week",
          name: "下周计划",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_wr_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "draft", name: "草稿", color: "amber" },
              { id: "submitted", name: "已提交", color: "emerald" },
            ],
          },
        },
      ],
    },

    // ── 合规审查 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_risks",
      nodeId: "nod_zh_base_risks",
      folderNodeId: "nod_compliance",
      slug: "risk-register",
      name: "风险登记册",
      description: "企业风险识别与缓解措施追踪，覆盖安全、合规、运营等维度。",
      useCases: ["compliance"],
      fields: [
        {
          id: "bsf_zh_rk_title",
          slug: "title",
          name: "风险描述",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_rk_category",
          slug: "category",
          name: "类别",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "security", name: "安全", color: "rose" },
              { id: "compliance", name: "合规", color: "amber" },
              { id: "ops", name: "运营", color: "blue" },
              { id: "finance", name: "财务", color: "emerald" },
              { id: "legal", name: "法律", color: "violet" },
            ],
          },
        },
        {
          id: "bsf_zh_rk_severity",
          slug: "severity",
          name: "严重程度",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "high", name: "高", color: "rose" },
              { id: "medium", name: "中", color: "amber" },
              { id: "low", name: "低", color: "emerald" },
            ],
          },
        },
        {
          id: "bsf_zh_rk_owner",
          slug: "owner",
          name: "责任人",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_rk_mitigation",
          slug: "mitigation",
          name: "缓解措施",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_rk_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "identified", name: "已识别", color: "amber" },
              { id: "mitigating", name: "处理中", color: "blue" },
              { id: "mitigated", name: "已缓解", color: "emerald" },
              { id: "closed", name: "已关闭", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_rk_contract_ref",
          slug: "contract-ref",
          name: "关联合同",
          type: "relation",
          required: false,
          options: { targetBaseId: "bse_zh_contracts" },
        },
      ],
    },
    {
      id: "bse_zh_contracts",
      nodeId: "nod_zh_base_contracts",
      folderNodeId: "nod_compliance",
      slug: "contract-ledger",
      name: "合同台账",
      description: "企业合同全生命周期管理，含金额、到期日与履约状态。",
      useCases: ["compliance"],
      fields: [
        {
          id: "bsf_zh_ct_name",
          slug: "name",
          name: "合同名称",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ct_party",
          slug: "party",
          name: "合作方",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ct_amount",
          slug: "amount",
          name: "合同金额（元）",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ct_type",
          slug: "type",
          name: "合同类型",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "service", name: "服务协议", color: "blue" },
              { id: "purchase", name: "采购合同", color: "emerald" },
              { id: "partnership", name: "合作协议", color: "violet" },
              { id: "nda", name: "保密协议", color: "amber" },
            ],
          },
        },
        {
          id: "bsf_zh_ct_start",
          slug: "start_date",
          name: "生效日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ct_end",
          slug: "end_date",
          name: "到期日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ct_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "draft", name: "草签", color: "amber" },
              { id: "active", name: "生效", color: "emerald" },
              { id: "expired", name: "已到期", color: "rose" },
              { id: "terminated", name: "已终止", color: "slate" },
            ],
          },
        },
      ],
    },

    // ── 市场研究 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_competitors",
      nodeId: "nod_zh_base_competitors",
      folderNodeId: "nod_research",
      slug: "competitor-analysis",
      name: "竞品分析",
      description: "主要竞争对手的产品特性、定价策略与市场定位对比。",
      useCases: ["research"],
      fields: [
        {
          id: "bsf_zh_ca_name",
          slug: "name",
          name: "公司/产品名称",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ca_category",
          slug: "category",
          name: "竞品类型",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "direct", name: "直接竞品", color: "rose" },
              { id: "indirect", name: "间接竞品", color: "amber" },
              { id: "alternative", name: "替代品", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_ca_strengths",
          slug: "strengths",
          name: "优势",
          type: "markdown",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ca_weaknesses",
          slug: "weaknesses",
          name: "劣势",
          type: "markdown",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ca_date",
          slug: "analyzed_at",
          name: "分析日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ca_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "ongoing", name: "进行中", color: "blue" },
              { id: "done", name: "已完成", color: "emerald" },
            ],
          },
        },
        {
          id: "bsf_zh_ca_interview_ref",
          slug: "interview-ref",
          name: "关联访谈",
          type: "relation",
          required: false,
          options: { targetBaseId: "bse_zh_interviews" },
        },
      ],
    },
    {
      id: "bse_zh_interviews",
      nodeId: "nod_zh_base_interviews",
      folderNodeId: "nod_research",
      slug: "user-interviews",
      name: "用户访谈",
      description: "目标用户深度访谈记录，提炼痛点、需求与洞察。",
      useCases: ["research"],
      fields: [
        {
          id: "bsf_zh_ui_interviewee",
          slug: "interviewee",
          name: "受访人",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ui_date",
          slug: "interview_date",
          name: "访谈日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ui_role",
          slug: "role",
          name: "职位/角色",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ui_insights",
          slug: "key_insights",
          name: "关键洞察",
          type: "markdown",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ui_pains",
          slug: "pain_points",
          name: "核心痛点",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ui_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "scheduled", name: "待安排", color: "amber" },
              { id: "done", name: "已完成", color: "emerald" },
              { id: "analyzed", name: "已分析", color: "blue" },
            ],
          },
        },
      ],
    },

    // ── 内容工厂 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_topics",
      nodeId: "nod_zh_base_topics",
      folderNodeId: "nod_content_factory",
      slug: "topic-ideas",
      name: "选题库",
      description: "内容选题创意池，按类别、优先级与发布状态管理。",
      useCases: ["content"],
      fields: [
        {
          id: "bsf_zh_tp_title",
          slug: "title",
          name: "选题标题",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_tp_category",
          slug: "category",
          name: "内容类别",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "insight", name: "行业洞察", color: "blue" },
              { id: "tutorial", name: "产品教程", color: "emerald" },
              { id: "case", name: "案例研究", color: "violet" },
              { id: "opinion", name: "观点文章", color: "amber" },
            ],
          },
        },
        {
          id: "bsf_zh_tp_source",
          slug: "source",
          name: "创意来源",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_tp_priority",
          slug: "priority",
          name: "优先级",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "high", name: "高", color: "rose" },
              { id: "medium", name: "中", color: "amber" },
              { id: "low", name: "低", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_tp_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "idea", name: "创意", color: "slate" },
              { id: "approved", name: "已批准", color: "blue" },
              { id: "writing", name: "撰写中", color: "amber" },
              { id: "published", name: "已发布", color: "emerald" },
            ],
          },
        },
        {
          id: "bsf_zh_tp_notes",
          slug: "notes",
          name: "备注",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_tp_editorial_ref",
          slug: "editorial-ref",
          name: "编辑日历条目",
          type: "relation",
          required: false,
          options: { targetBaseId: "bse_zh_editorial" },
        },
      ],
    },
    {
      id: "bse_zh_editorial",
      nodeId: "nod_zh_base_editorial",
      folderNodeId: "nod_content_factory",
      slug: "editorial-calendar",
      name: "编辑日历",
      description: "内容发布日历，按渠道、日期与责任人规划所有内容产出。",
      useCases: ["content"],
      fields: [
        {
          id: "bsf_zh_ec_title",
          slug: "title",
          name: "内容标题",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ec_type",
          slug: "content_type",
          name: "内容类型",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "blog", name: "博客", color: "blue" },
              { id: "video", name: "视频", color: "violet" },
              { id: "social", name: "社媒", color: "emerald" },
              { id: "email", name: "邮件", color: "amber" },
              { id: "whitepaper", name: "白皮书", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_zh_ec_channel",
          slug: "channel",
          name: "发布渠道",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ec_publish",
          slug: "publish_date",
          name: "计划发布日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ec_author",
          slug: "author",
          name: "作者",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ec_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "planned", name: "规划中", color: "slate" },
              { id: "writing", name: "撰写中", color: "amber" },
              { id: "review", name: "审核中", color: "blue" },
              { id: "published", name: "已发布", color: "emerald" },
            ],
          },
        },
      ],
    },

    // ── 数据集库 ──────────────────────────────────────────────────────────────
    {
      id: "bse_zh_evals",
      nodeId: "nod_zh_base_evals",
      folderNodeId: "nod_datasets",
      slug: "model-evals",
      name: "模型评估记录",
      description: "各版本模型在不同任务与基准测试上的评估得分与分析。",
      useCases: ["dataset"],
      fields: [
        {
          id: "bsf_zh_ev2_model",
          slug: "model",
          name: "模型名称",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ev2_task",
          slug: "task",
          name: "评估任务",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_zh_ev2_score",
          slug: "score",
          name: "得分",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ev2_benchmark",
          slug: "benchmark",
          name: "基准测试",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ev2_date",
          slug: "eval_date",
          name: "评估日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_zh_ev2_notes",
          slug: "notes",
          name: "备注",
          type: "text",
          required: false,
          options: {},
        },
      ],
    },
  ],

  records: [
    // 费用报销
    {
      id: "rec_zh_exp_001",
      baseId: "bse_zh_expense",
      commitId: "cmt_zh_exp_001",
      minutesAgo: 200,
      message: "提交差旅报销：出差上海参加产品峰会",
      author: "王小明",
      useCases: ["finance"],
      fields: {
        title: "上海产品峰会差旅",
        amount: 3280,
        category: "travel",
        applicant: "王小明",
        apply_date: "2026-06-10",
        status: "approved",
        notes: "含高铁+酒店两晚",
      },
    },
    {
      id: "rec_zh_exp_002",
      baseId: "bse_zh_expense",
      commitId: "cmt_zh_exp_002",
      minutesAgo: 150,
      message: "提交团队餐饮报销",
      author: "李雪",
      useCases: ["finance"],
      fields: {
        title: "季度团队聚餐",
        amount: 1560,
        category: "meal",
        applicant: "李雪",
        apply_date: "2026-06-15",
        status: "pending",
        notes: "12人，人均130元",
      },
    },
    {
      id: "rec_zh_exp_003",
      baseId: "bse_zh_expense",
      commitId: "cmt_zh_exp_003",
      minutesAgo: 80,
      message: "办公用品采购报销",
      author: "陈伟",
      useCases: ["finance"],
      fields: {
        title: "工位显示器支架 ×3",
        amount: 450,
        category: "office",
        applicant: "陈伟",
        apply_date: "2026-06-18",
        status: "reimbursed",
        notes: "已对账",
      },
    },

    // 会议纪要
    {
      id: "rec_zh_mtg_001",
      baseId: "bse_zh_meeting",
      commitId: "cmt_zh_mtg_001",
      minutesAgo: 300,
      message: "记录 Q3 产品规划会",
      author: "产品团队",
      useCases: ["knowledge"],
      fields: {
        title: "Q3 产品路线图评审",
        date: "2026-06-12",
        attendees: "张总、产品组全员、研发负责人",
        summary:
          "## 结论\n\n- 确认 Q3 核心目标为数据协作体验升级\n- AI 审批辅助功能列入 7 月 milestone\n- 移动端适配延至 Q4",
        action_items: "产品出 PRD（6/20前）；研发评估工期（6/25前）",
        status: "confirmed",
      },
    },
    {
      id: "rec_zh_mtg_002",
      baseId: "bse_zh_meeting",
      commitId: "cmt_zh_mtg_002",
      minutesAgo: 120,
      message: "记录周一站会纪要",
      author: "项目经理",
      useCases: ["knowledge"],
      fields: {
        title: "技术周一例会 2026-W25",
        date: "2026-06-17",
        attendees: "研发组 7 人",
        summary:
          "## 本周进展\n\n- 审批流重构完成 80%\n- 前端字段类型组件库提测\n- CI 流水线优化上线",
        action_items: "修复 inbox 过滤器 bug（王工负责）；更新部署文档",
        status: "confirmed",
      },
    },
    {
      id: "rec_zh_mtg_003",
      baseId: "bse_zh_meeting",
      commitId: "cmt_zh_mtg_003",
      minutesAgo: 60,
      message: "记录市场对齐会议",
      author: "市场团队",
      useCases: ["knowledge"],
      fields: {
        title: "H2 市场策略对齐会",
        date: "2026-06-20",
        attendees: "市场、销售、CEO",
        summary:
          "## 决策\n\n- 聚焦中大型企业 AI 数据协作场景\n- KOL 合作预算批准 30 万\n- 产品 Hunt 活动定档 8 月",
        action_items: "市场出执行计划（6/30）；确定 KOL 候选名单",
        status: "draft",
      },
    },

    // 项目文档
    {
      id: "rec_zh_pd_001",
      baseId: "bse_zh_projdoc",
      commitId: "cmt_zh_pd_001",
      minutesAgo: 500,
      message: "创建数据协作模块 PRD",
      author: "产品经理",
      useCases: ["knowledge"],
      fields: {
        title: "数据协作模块 PRD v1.2",
        project: "Busabase 核心",
        type: "spec",
        version: "1.2",
        content:
          "## 背景\n\n当前审批流缺少批量操作能力，导致大数据量场景下用户效率低下。\n\n## 目标\n\n支持单次提交多条记录变更，审批人可批量 approve/reject。\n\n## 核心功能\n\n1. 批量 CR 提交\n2. 审批看板视图\n3. 冲突检测与合并策略",
        status: "review",
      },
    },
    {
      id: "rec_zh_pd_002",
      baseId: "bse_zh_projdoc",
      commitId: "cmt_zh_pd_002",
      minutesAgo: 250,
      message: "上传 AI 审批辅助设计方案",
      author: "设计师",
      useCases: ["knowledge"],
      fields: {
        title: "AI 审批辅助 UI 方案",
        project: "AI 功能增强",
        type: "design",
        version: "0.3",
        content:
          "## 设计目标\n\n降低审批人决策负担，AI 提供变更摘要与风险提示。\n\n## 交互流程\n\n1. 审批人进入 CR 详情\n2. AI 侧边栏展示变更影响分析\n3. 一键接受 AI 建议 / 手动覆盖",
        status: "published",
      },
    },

    // 活动策划
    {
      id: "rec_zh_ev_001",
      baseId: "bse_zh_events",
      commitId: "cmt_zh_ev_001",
      minutesAgo: 400,
      message: "新建 AI 数据峰会活动",
      author: "市场专员",
      useCases: ["operations"],
      fields: {
        name: "2026 AI 数据协作峰会",
        type: "offline",
        event_date: "2026-08-15",
        budget: 80000,
        owner: "李雪",
        description: "面向企业数据负责人的行业峰会，预计到场 300+人",
        status: "planning",
      },
    },
    {
      id: "rec_zh_ev_002",
      baseId: "bse_zh_events",
      commitId: "cmt_zh_ev_002",
      minutesAgo: 200,
      message: "创建产品线上发布会计划",
      author: "产品运营",
      useCases: ["operations"],
      fields: {
        name: "Busabase v2.0 线上发布会",
        type: "online",
        event_date: "2026-07-10",
        budget: 15000,
        owner: "张宇",
        description: "通过直播形式发布新版本，预计观看人数 5000+",
        status: "ongoing",
      },
    },
    {
      id: "rec_zh_ev_003",
      baseId: "bse_zh_events",
      commitId: "cmt_zh_ev_003",
      minutesAgo: 100,
      message: "记录客户茶话会",
      author: "客户成功",
      useCases: ["operations"],
      fields: {
        name: "核心客户季度茶话会",
        type: "offline",
        event_date: "2026-06-28",
        budget: 8000,
        owner: "王晓",
        description: "邀请 20 家核心客户代表深度交流产品使用体验",
        status: "done",
      },
    },

    // 渠道管理
    {
      id: "rec_zh_ch_001",
      baseId: "bse_zh_channels",
      commitId: "cmt_zh_ch_001",
      minutesAgo: 350,
      message: "登记微信公众号渠道",
      author: "市场",
      useCases: ["operations"],
      fields: {
        name: "Busabase 官方公众号",
        platform: "wechat",
        owner: "内容组",
        monthly_goal: 50000,
        status: "active",
        notes: "粉丝 12万，周更频率",
      },
    },
    {
      id: "rec_zh_ch_002",
      baseId: "bse_zh_channels",
      commitId: "cmt_zh_ch_002",
      minutesAgo: 200,
      message: "登记抖音渠道",
      author: "市场",
      useCases: ["operations"],
      fields: {
        name: "Busabase 抖音号",
        platform: "douyin",
        owner: "视频组",
        monthly_goal: 100000,
        status: "active",
        notes: "主推产品功能演示短视频",
      },
    },
    {
      id: "rec_zh_ch_003",
      baseId: "bse_zh_channels",
      commitId: "cmt_zh_ch_003",
      minutesAgo: 100,
      message: "登记 LinkedIn 渠道",
      author: "市场",
      useCases: ["operations"],
      fields: {
        name: "Busabase LinkedIn",
        platform: "linkedin",
        owner: "国际市场",
        monthly_goal: 5000,
        status: "paused",
        notes: "待国际化版本发布后重启",
      },
    },

    // 待办事项
    {
      id: "rec_zh_td_001",
      baseId: "bse_zh_todos",
      commitId: "cmt_zh_td_001",
      minutesAgo: 180,
      message: "添加 inbox 过滤器修复任务",
      author: "研发",
      useCases: ["routine"],
      fields: {
        title: "修复 inbox 过滤按钮无响应问题",
        priority: "high",
        due_date: "2026-06-23",
        assignee: "王工",
        status: "in_progress",
        description: "wouter useSearch bug，tab 参数未生效",
      },
    },
    {
      id: "rec_zh_td_002",
      baseId: "bse_zh_todos",
      commitId: "cmt_zh_td_002",
      minutesAgo: 120,
      message: "添加文档更新任务",
      author: "产品",
      useCases: ["routine"],
      fields: {
        title: "更新 API 文档 — 新增 batch CR 接口",
        priority: "medium",
        due_date: "2026-06-30",
        assignee: "文档组",
        status: "open",
        description: "需覆盖 POST /bases/{id}/change-requests 批量操作",
      },
    },
    {
      id: "rec_zh_td_003",
      baseId: "bse_zh_todos",
      commitId: "cmt_zh_td_003",
      minutesAgo: 60,
      message: "添加上线前 checklist",
      author: "QA",
      useCases: ["routine"],
      fields: {
        title: "v2.0 发布前回归测试",
        priority: "high",
        due_date: "2026-07-08",
        assignee: "QA 团队",
        status: "open",
        description: "覆盖审批流、字段类型、视图过滤三大模块",
      },
    },

    // 周报记录
    {
      id: "rec_zh_wr_001",
      baseId: "bse_zh_weekly",
      commitId: "cmt_zh_wr_001",
      minutesAgo: 240,
      message: "提交 W24 周报",
      author: "项目经理",
      useCases: ["routine"],
      fields: {
        period: "2026-W24（6/10-6/16）",
        highlights:
          "## 本周亮点\n\n- 完成数据表字段类型扩展（新增 phone/email/url）\n- 审批流批量操作完成设计评审\n- CI 流水线平均构建时间降低 40%",
        blockers: "移动端适配受限于设计资源，延期至下周",
        next_week: "推进 AI 摘要字段接入测试；修复 inbox 已知 bug",
        status: "submitted",
      },
    },
    {
      id: "rec_zh_wr_002",
      baseId: "bse_zh_weekly",
      commitId: "cmt_zh_wr_002",
      minutesAgo: 100,
      message: "提交 W25 周报",
      author: "项目经理",
      useCases: ["routine"],
      fields: {
        period: "2026-W25（6/17-6/23）",
        highlights:
          "## 本周亮点\n\n- inbox 过滤器 bug 修复上线\n- 中文 demo 数据集完成（71条数据，全部通过 OpenAPI 审批流写入）\n- db:seed / demo 架构分层重构完成",
        blockers: "暂无重大阻碍",
        next_week: "完善 demo 数据量；启动 v2.0 发布会准备",
        status: "draft",
      },
    },

    // 风险登记册
    {
      id: "rec_zh_rk_001",
      baseId: "bse_zh_risks",
      commitId: "cmt_zh_rk_001",
      minutesAgo: 600,
      message: "登记数据泄露风险",
      author: "安全团队",
      useCases: ["compliance"],
      fields: {
        title: "第三方 API 密钥硬编码风险",
        category: "security",
        severity: "high",
        owner: "CTO",
        mitigation: "推行密钥管理平台，禁止明文提交；已配置 git-secrets 扫描",
        status: "mitigating",
      },
    },
    {
      id: "rec_zh_rk_002",
      baseId: "bse_zh_risks",
      commitId: "cmt_zh_rk_002",
      minutesAgo: 400,
      message: "登记合规风险",
      author: "法务",
      useCases: ["compliance"],
      fields: {
        title: "个人数据跨境传输合规风险",
        category: "compliance",
        severity: "medium",
        owner: "法务总监",
        mitigation: "完成数据本地化存储方案设计；正在申请 PIPL 合规认证",
        status: "mitigating",
      },
    },
    {
      id: "rec_zh_rk_003",
      baseId: "bse_zh_risks",
      commitId: "cmt_zh_rk_003",
      minutesAgo: 200,
      message: "登记关键人员流失风险",
      author: "HR",
      useCases: ["compliance"],
      fields: {
        title: "核心研发人员流失风险",
        category: "ops",
        severity: "medium",
        owner: "HR 总监",
        mitigation: "已启动期权激励方案；关键岗位 backup 计划进行中",
        status: "identified",
      },
    },

    // 合同台账
    {
      id: "rec_zh_ct_001",
      baseId: "bse_zh_contracts",
      commitId: "cmt_zh_ct_001",
      minutesAgo: 700,
      message: "录入阿里云服务协议",
      author: "采购",
      useCases: ["compliance"],
      fields: {
        name: "阿里云企业版服务协议 2026",
        party: "阿里云计算有限公司",
        amount: 240000,
        type: "service",
        start_date: "2026-01-01",
        end_date: "2026-12-31",
        status: "active",
      },
    },
    {
      id: "rec_zh_ct_002",
      baseId: "bse_zh_contracts",
      commitId: "cmt_zh_ct_002",
      minutesAgo: 500,
      message: "录入设计外包合同",
      author: "采购",
      useCases: ["compliance"],
      fields: {
        name: "品牌 VI 设计外包合同",
        party: "北京某某设计工作室",
        amount: 85000,
        type: "purchase",
        start_date: "2026-05-01",
        end_date: "2026-08-31",
        status: "active",
      },
    },
    {
      id: "rec_zh_ct_003",
      baseId: "bse_zh_contracts",
      commitId: "cmt_zh_ct_003",
      minutesAgo: 300,
      message: "录入战略合作协议",
      author: "BD",
      useCases: ["compliance"],
      fields: {
        name: "某头部企业服务商战略合作协议",
        party: "上海某某科技有限公司",
        amount: 500000,
        type: "partnership",
        start_date: "2026-06-01",
        end_date: "2027-05-31",
        status: "active",
      },
    },

    // 竞品分析
    {
      id: "rec_zh_ca_001",
      baseId: "bse_zh_competitors",
      commitId: "cmt_zh_ca_001",
      minutesAgo: 800,
      message: "完成 Airtable 竞品分析",
      author: "市场分析师",
      useCases: ["research"],
      fields: {
        name: "Airtable",
        category: "direct",
        strengths:
          "## 优势\n\n- 生态成熟，插件市场丰富\n- 品牌认知度高（尤其北美市场）\n- 非技术用户友好的 UI",
        weaknesses:
          "## 劣势\n\n- 价格偏高，中国本土化弱\n- 审批流需额外配置，不是核心能力\n- AI 能力后发，集成体验割裂",
        analyzed_at: "2026-05-20",
        status: "done",
      },
    },
    {
      id: "rec_zh_ca_002",
      baseId: "bse_zh_competitors",
      commitId: "cmt_zh_ca_002",
      minutesAgo: 600,
      message: "完成飞书多维表格竞品分析",
      author: "市场分析师",
      useCases: ["research"],
      fields: {
        name: "飞书多维表格",
        category: "direct",
        strengths:
          "## 优势\n\n- 深度集成飞书 IM 生态\n- 本土化强，中文支持完善\n- 企业客户获取成本低（捆绑销售）",
        weaknesses:
          "## 劣势\n\n- 审批流功能弱，依赖飞书审批单独模块\n- AI 数据治理能力不足\n- 开放 API 限制较多",
        analyzed_at: "2026-06-01",
        status: "done",
      },
    },
    {
      id: "rec_zh_ca_003",
      baseId: "bse_zh_competitors",
      commitId: "cmt_zh_ca_003",
      minutesAgo: 300,
      message: "进行 Notion Database 分析",
      author: "市场分析师",
      useCases: ["research"],
      fields: {
        name: "Notion Database",
        category: "indirect",
        strengths: "## 优势\n\n- 个人用户极高黏性\n- 知识管理与数据库一体化\n- 模板生态活跃",
        weaknesses: "## 劣势\n\n- 企业权限管理弱\n- 无原生审批流\n- 大数据量性能差",
        analyzed_at: "2026-06-15",
        status: "ongoing",
      },
    },

    // 用户访谈
    {
      id: "rec_zh_ui_001",
      baseId: "bse_zh_interviews",
      commitId: "cmt_zh_ui_001",
      minutesAgo: 500,
      message: "记录某物流公司数据主管访谈",
      author: "产品经理",
      useCases: ["research"],
      fields: {
        interviewee: "张建国（物流科技 - 数据中台负责人）",
        interview_date: "2026-06-05",
        role: "数据中台负责人",
        key_insights:
          "## 关键洞察\n\n- 每日处理 20+ 张运营报表，人工校对耗时 3-4 小时\n- 数据变更需经过 3 级审批，现靠钉钉流程，易出错\n- 最期待：字段级变更追踪 + 批量审批 + 异常自动提醒",
        pain_points: "审批链条长、变更无追溯、不同部门版本不一致",
        status: "analyzed",
      },
    },
    {
      id: "rec_zh_ui_002",
      baseId: "bse_zh_interviews",
      commitId: "cmt_zh_ui_002",
      minutesAgo: 300,
      message: "记录某律所信息化负责人访谈",
      author: "产品经理",
      useCases: ["research"],
      fields: {
        interviewee: "李慧敏（某律所 - IT 总监）",
        interview_date: "2026-06-12",
        role: "IT 总监",
        key_insights:
          "## 关键洞察\n\n- 案件信息高度敏感，需要精细化权限控制\n- 合同台账目前用 Excel，版本混乱\n- 希望有完整的操作审计日志供合规备查",
        pain_points: "权限粒度不够细、审计日志缺失、Excel 协作效率低",
        status: "analyzed",
      },
    },
    {
      id: "rec_zh_ui_003",
      baseId: "bse_zh_interviews",
      commitId: "cmt_zh_ui_003",
      minutesAgo: 100,
      message: "记录某互联网公司产品经理访谈",
      author: "用户研究",
      useCases: ["research"],
      fields: {
        interviewee: "王芳（某互联网公司高级 PM）",
        interview_date: "2026-06-19",
        role: "高级产品经理",
        key_insights:
          "## 关键洞察\n\n- 管理 10+ 个数据表，字段类型需求多样（富文本、关系型）\n- 想要 AI 帮助自动生成数据摘要，减少人工阅读量\n- 视图过滤功能是日常工作刚需",
        pain_points: "缺少 AI 辅助摘要、视图配置不够灵活、移动端体验差",
        status: "done",
      },
    },

    // 选题库
    {
      id: "rec_zh_tp_001",
      baseId: "bse_zh_topics",
      commitId: "cmt_zh_tp_001",
      minutesAgo: 400,
      message: "提交 AI 数据治理系列选题",
      author: "内容策划",
      useCases: ["content"],
      fields: {
        title: "AI 时代，企业数据治理为何成为核心竞争力？",
        category: "insight",
        source: "用户访谈 + 行业报告",
        priority: "high",
        status: "approved",
        notes: "配合 Q3 市场活动，8月上线",
      },
    },
    {
      id: "rec_zh_tp_002",
      baseId: "bse_zh_topics",
      commitId: "cmt_zh_tp_002",
      minutesAgo: 250,
      message: "提交产品教程选题",
      author: "内容策划",
      useCases: ["content"],
      fields: {
        title: "5 分钟上手 Busabase 审批流：从创建到合并全流程",
        category: "tutorial",
        source: "产品团队建议",
        priority: "high",
        status: "writing",
        notes: "搭配截图 + GIF 演示",
      },
    },
    {
      id: "rec_zh_tp_003",
      baseId: "bse_zh_topics",
      commitId: "cmt_zh_tp_003",
      minutesAgo: 120,
      message: "提交案例研究选题",
      author: "内容策划",
      useCases: ["content"],
      fields: {
        title: "某物流科技如何用 Busabase 将数据审批效率提升 60%",
        category: "case",
        source: "客户成功团队",
        priority: "medium",
        status: "idea",
        notes: "需客户授权后启动",
      },
    },

    // 编辑日历
    {
      id: "rec_zh_ec_001",
      baseId: "bse_zh_editorial",
      commitId: "cmt_zh_ec_001",
      minutesAgo: 350,
      message: "排期博客文章",
      author: "编辑",
      useCases: ["content"],
      fields: {
        title: "AI 时代数据治理核心竞争力",
        content_type: "blog",
        channel: "官网博客 + 微信",
        publish_date: "2026-08-05",
        author: "张明",
        status: "writing",
      },
    },
    {
      id: "rec_zh_ec_002",
      baseId: "bse_zh_editorial",
      commitId: "cmt_zh_ec_002",
      minutesAgo: 200,
      message: "排期产品演示视频",
      author: "视频编辑",
      useCases: ["content"],
      fields: {
        title: "Busabase 审批流 5 分钟上手教程",
        content_type: "video",
        channel: "抖音 + B站",
        publish_date: "2026-07-20",
        author: "视频组",
        status: "review",
      },
    },
    {
      id: "rec_zh_ec_003",
      baseId: "bse_zh_editorial",
      commitId: "cmt_zh_ec_003",
      minutesAgo: 80,
      message: "排期发布会邮件",
      author: "市场",
      useCases: ["content"],
      fields: {
        title: "Busabase v2.0 发布邀请函",
        content_type: "email",
        channel: "邮件列表",
        publish_date: "2026-07-08",
        author: "市场组",
        status: "planned",
      },
    },

    // 模型评估记录
    {
      id: "rec_zh_ev2_001",
      baseId: "bse_zh_evals",
      commitId: "cmt_zh_ev2_001",
      minutesAgo: 600,
      message: "记录 GPT-4o 摘要任务评估",
      author: "AI 工程师",
      useCases: ["dataset"],
      fields: {
        model: "GPT-4o",
        task: "数据记录自动摘要",
        score: 87.3,
        benchmark: "内部评测集 v2.1",
        eval_date: "2026-06-10",
        notes: "中文摘要质量优秀，偶有信息遗漏",
      },
    },
    {
      id: "rec_zh_ev2_002",
      baseId: "bse_zh_evals",
      commitId: "cmt_zh_ev2_002",
      minutesAgo: 400,
      message: "记录 Claude 审批建议评估",
      author: "AI 工程师",
      useCases: ["dataset"],
      fields: {
        model: "claude-sonnet-4-6",
        task: "变更风险评估与审批建议",
        score: 91.5,
        benchmark: "内部评测集 v2.1",
        eval_date: "2026-06-14",
        notes: "风险识别准确率最高，推荐作为主力模型",
      },
    },
    {
      id: "rec_zh_ev2_003",
      baseId: "bse_zh_evals",
      commitId: "cmt_zh_ev2_003",
      minutesAgo: 200,
      message: "记录 Qwen2.5 中文标签任务评估",
      author: "AI 工程师",
      useCases: ["dataset"],
      fields: {
        model: "Qwen2.5-72B",
        task: "中文内容自动打标",
        score: 83.8,
        benchmark: "内部评测集 v2.1",
        eval_date: "2026-06-18",
        notes: "成本最优，适合高频低复杂度标注场景",
      },
    },
  ],

  views: [
    // 费用报销
    {
      id: "viw_zh_exp_all",
      baseId: "bse_zh_expense",
      slug: "all-expenses",
      name: "全部报销",
      description: "",
      minutesAgo: 190,
      useCases: ["finance"],
      config: { filters: [], sorts: [{ fieldSlug: "apply_date", direction: "desc" }] },
    },
    {
      id: "viw_zh_exp_pending",
      baseId: "bse_zh_expense",
      slug: "pending-review",
      name: "待审核",
      description: "",
      minutesAgo: 185,
      useCases: ["finance"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "pending" }],
        sorts: [],
      },
    },

    // 会议纪要
    {
      id: "viw_zh_mtg_all",
      baseId: "bse_zh_meeting",
      slug: "all-meetings",
      name: "全部会议",
      description: "",
      minutesAgo: 290,
      useCases: ["knowledge"],
      config: { filters: [], sorts: [{ fieldSlug: "date", direction: "desc" }] },
    },
    {
      id: "viw_zh_mtg_draft",
      baseId: "bse_zh_meeting",
      slug: "drafts",
      name: "草稿待确认",
      description: "",
      minutesAgo: 285,
      useCases: ["knowledge"],
      config: { filters: [{ fieldSlug: "status", operator: "equals", value: "draft" }], sorts: [] },
    },

    // 项目文档
    {
      id: "viw_zh_pd_all",
      baseId: "bse_zh_projdoc",
      slug: "all-docs",
      name: "全部文档",
      description: "",
      minutesAgo: 490,
      useCases: ["knowledge"],
      config: { filters: [], sorts: [{ fieldSlug: "status", direction: "asc" }] },
    },
    {
      id: "viw_zh_pd_review",
      baseId: "bse_zh_projdoc",
      slug: "in-review",
      name: "评审中",
      description: "",
      minutesAgo: 485,
      useCases: ["knowledge"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "review" }],
        sorts: [],
      },
    },

    // 活动策划
    {
      id: "viw_zh_ev_all",
      baseId: "bse_zh_events",
      slug: "all-events",
      name: "全部活动",
      description: "",
      minutesAgo: 390,
      useCases: ["operations"],
      config: { filters: [], sorts: [{ fieldSlug: "event_date", direction: "asc" }] },
    },
    {
      id: "viw_zh_ev_upcoming",
      baseId: "bse_zh_events",
      slug: "upcoming",
      name: "即将举行",
      description: "",
      minutesAgo: 385,
      useCases: ["operations"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "planning" }],
        sorts: [{ fieldSlug: "event_date", direction: "asc" }],
      },
    },

    // 渠道管理
    {
      id: "viw_zh_ch_all",
      baseId: "bse_zh_channels",
      slug: "all-channels",
      name: "全部渠道",
      description: "",
      minutesAgo: 340,
      useCases: ["operations"],
      config: { filters: [], sorts: [] },
    },
    {
      id: "viw_zh_ch_active",
      baseId: "bse_zh_channels",
      slug: "active-channels",
      name: "活跃渠道",
      description: "",
      minutesAgo: 335,
      useCases: ["operations"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "active" }],
        sorts: [],
      },
    },

    // 待办事项
    {
      id: "viw_zh_td_all",
      baseId: "bse_zh_todos",
      slug: "all-todos",
      name: "全部待办",
      description: "",
      minutesAgo: 170,
      useCases: ["routine"],
      config: { filters: [], sorts: [{ fieldSlug: "priority", direction: "asc" }] },
    },
    {
      id: "viw_zh_td_open",
      baseId: "bse_zh_todos",
      slug: "open-todos",
      name: "未完成",
      description: "",
      minutesAgo: 165,
      useCases: ["routine"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "open" }],
        sorts: [{ fieldSlug: "due_date", direction: "asc" }],
      },
    },

    // 周报记录
    {
      id: "viw_zh_wr_all",
      baseId: "bse_zh_weekly",
      slug: "all-reports",
      name: "全部周报",
      description: "",
      minutesAgo: 230,
      useCases: ["routine"],
      config: { filters: [], sorts: [{ fieldSlug: "period", direction: "desc" }] },
    },

    // 风险登记册
    {
      id: "viw_zh_rk_all",
      baseId: "bse_zh_risks",
      slug: "all-risks",
      name: "全部风险",
      description: "",
      minutesAgo: 590,
      useCases: ["compliance"],
      config: { filters: [], sorts: [] },
    },
    {
      id: "viw_zh_rk_high",
      baseId: "bse_zh_risks",
      slug: "high-risks",
      name: "高危风险",
      description: "",
      minutesAgo: 585,
      useCases: ["compliance"],
      config: {
        filters: [{ fieldSlug: "severity", operator: "equals", value: "high" }],
        sorts: [],
      },
    },

    // 合同台账
    {
      id: "viw_zh_ct_all",
      baseId: "bse_zh_contracts",
      slug: "all-contracts",
      name: "全部合同",
      description: "",
      minutesAgo: 690,
      useCases: ["compliance"],
      config: { filters: [], sorts: [{ fieldSlug: "end_date", direction: "asc" }] },
    },
    {
      id: "viw_zh_ct_active",
      baseId: "bse_zh_contracts",
      slug: "active-contracts",
      name: "生效合同",
      description: "",
      minutesAgo: 685,
      useCases: ["compliance"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "active" }],
        sorts: [],
      },
    },

    // 竞品分析
    {
      id: "viw_zh_ca_all",
      baseId: "bse_zh_competitors",
      slug: "all-competitors",
      name: "全部竞品",
      description: "",
      minutesAgo: 790,
      useCases: ["research"],
      config: { filters: [], sorts: [] },
    },
    {
      id: "viw_zh_ca_direct",
      baseId: "bse_zh_competitors",
      slug: "direct-competitors",
      name: "直接竞品",
      description: "",
      minutesAgo: 785,
      useCases: ["research"],
      config: {
        filters: [{ fieldSlug: "category", operator: "equals", value: "direct" }],
        sorts: [],
      },
    },

    // 用户访谈
    {
      id: "viw_zh_ui_all",
      baseId: "bse_zh_interviews",
      slug: "all-interviews",
      name: "全部访谈",
      description: "",
      minutesAgo: 490,
      useCases: ["research"],
      config: { filters: [], sorts: [{ fieldSlug: "interview_date", direction: "desc" }] },
    },
    {
      id: "viw_zh_ui_analyzed",
      baseId: "bse_zh_interviews",
      slug: "analyzed",
      name: "已分析",
      description: "",
      minutesAgo: 485,
      useCases: ["research"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "analyzed" }],
        sorts: [],
      },
    },

    // 选题库
    {
      id: "viw_zh_tp_all",
      baseId: "bse_zh_topics",
      slug: "all-topics",
      name: "全部选题",
      description: "",
      minutesAgo: 390,
      useCases: ["content"],
      config: { filters: [], sorts: [{ fieldSlug: "priority", direction: "asc" }] },
    },
    {
      id: "viw_zh_tp_approved",
      baseId: "bse_zh_topics",
      slug: "approved-topics",
      name: "已批准选题",
      description: "",
      minutesAgo: 385,
      useCases: ["content"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "approved" }],
        sorts: [],
      },
    },

    // 编辑日历
    {
      id: "viw_zh_ec_all",
      baseId: "bse_zh_editorial",
      slug: "all-content",
      name: "全部内容",
      description: "",
      minutesAgo: 340,
      useCases: ["content"],
      config: { filters: [], sorts: [{ fieldSlug: "publish_date", direction: "asc" }] },
    },
    {
      id: "viw_zh_ec_review",
      baseId: "bse_zh_editorial",
      slug: "in-review",
      name: "审核中",
      description: "",
      minutesAgo: 335,
      useCases: ["content"],
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "review" }],
        sorts: [],
      },
    },

    // 模型评估记录
    {
      id: "viw_zh_ev2_all",
      baseId: "bse_zh_evals",
      slug: "all-evals",
      name: "全部评估",
      description: "",
      minutesAgo: 590,
      useCases: ["dataset"],
      config: { filters: [], sorts: [{ fieldSlug: "score", direction: "desc" }] },
    },
  ],
};
