import type { SeedScenario } from "../seed-types";
import {
  DEMO_INVOICES_BASE_ID,
  DEMO_INVOICES_BASE_NODE_ID,
  DEMO_PURCHASE_ORDERS_BASE_ID,
  DEMO_PURCHASE_ORDERS_BASE_NODE_ID,
  FINANCE_INVOICE_FIGMA_ID,
  FINANCE_INVOICE_GLOBEX_ID,
  FINANCE_INVOICE_REVIEW_ID,
  FINANCE_PO_DESIGN_ID,
  FINANCE_PO_PLATFORM_ID,
} from "./finance-invoice";

const FINANCE_FOLDER_NODE_ID = "nod_finance";
const PO_PLATFORM_COMMIT_ID = "cmt_seed_po_platform";
const PO_DESIGN_COMMIT_ID = "cmt_seed_po_design";
const INVOICE_GLOBEX_COMMIT_ID = "cmt_seed_invoice_globex_cloud";
const INVOICE_FIGMA_COMMIT_ID = "cmt_seed_invoice_figma_seats";

export const financeInvoiceZhCnScenario: SeedScenario = {
  folders: [
    {
      nodeId: FINANCE_FOLDER_NODE_ID,
      slug: "finance",
      name: "财务管理",
      description: "发票、采购订单、报销凭证和付款审批。",
      position: 2,
    },
  ],

  bases: [
    {
      id: DEMO_PURCHASE_ORDERS_BASE_ID,
      nodeId: DEMO_PURCHASE_ORDERS_BASE_NODE_ID,
      slug: "purchase-orders",
      name: "采购订单",
      description: "已审批的采购订单，用于发票三方比对核验。",
      folderNodeId: FINANCE_FOLDER_NODE_ID,
      useCases: ["finance"],
      fields: [
        {
          id: "bsf_po_number",
          slug: "po_number",
          name: "采购单号",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_po_vendor",
          slug: "vendor",
          name: "供应商",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_po_owner",
          slug: "owner",
          name: "负责人",
          type: "email",
          required: false,
          options: {},
        },
        {
          id: "bsf_po_budget",
          slug: "budget",
          name: "预算金额",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_po_currency",
          slug: "currency",
          name: "币种",
          type: "text",
          required: false,
          options: {},
        },
        {
          id: "bsf_po_approved_at",
          slug: "approved_at",
          name: "审批日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_po_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "open", name: "进行中", color: "amber" },
              { id: "matched", name: "已匹配", color: "emerald" },
              { id: "closed", name: "已关闭", color: "slate" },
            ],
          },
        },
      ],
    },
    {
      id: DEMO_INVOICES_BASE_ID,
      nodeId: DEMO_INVOICES_BASE_NODE_ID,
      slug: "invoices",
      name: "发票管理",
      description: "待财务审核、采购匹配和付款审批的发票记录。",
      folderNodeId: FINANCE_FOLDER_NODE_ID,
      useCases: ["finance"],
      fields: [
        {
          id: "bsf_invoice_number",
          slug: "invoice_number",
          name: "发票编号",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_invoice_vendor",
          slug: "vendor",
          name: "供应商",
          type: "text",
          required: true,
          options: {},
        },
        {
          id: "bsf_invoice_po",
          slug: "purchase-order",
          name: "关联采购订单",
          type: "relation",
          required: false,
          options: { multiple: false, targetBaseId: DEMO_PURCHASE_ORDERS_BASE_ID },
        },
        {
          id: "bsf_invoice_amount",
          slug: "amount",
          name: "金额",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_invoice_tax",
          slug: "tax",
          name: "税额",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_invoice_total",
          slug: "total",
          name: "合计",
          type: "number",
          required: false,
          options: {},
        },
        {
          id: "bsf_invoice_due_date",
          slug: "due_date",
          name: "到期日期",
          type: "date",
          required: false,
          options: {},
        },
        {
          id: "bsf_invoice_attachment",
          slug: "invoice_file",
          name: "发票文件",
          type: "attachment",
          required: false,
          options: {
            attachment: {
              allowedMimeTypes: ["application/pdf", "image/png"],
              maxFileSize: 15 * 1024 * 1024,
              maxFiles: 3,
            },
          },
        },
        {
          id: "bsf_invoice_status",
          slug: "status",
          name: "状态",
          type: "select",
          required: false,
          options: {
            choices: [
              { id: "needs-review", name: "待审核", color: "amber" },
              { id: "matched", name: "已匹配", color: "emerald" },
              { id: "exception", name: "有异常", color: "rose" },
              { id: "paid", name: "已付款", color: "slate" },
            ],
          },
        },
        {
          id: "bsf_invoice_flags",
          slug: "flags",
          name: "异常标记",
          type: "multiselect",
          required: false,
          options: {
            choices: [
              { id: "amount-mismatch", name: "金额不符", color: "rose" },
              { id: "tax-check", name: "税务核查", color: "amber" },
              { id: "po-match", name: "PO匹配", color: "emerald" },
            ],
          },
        },
        {
          id: "bsf_invoice_paid",
          slug: "ready_to_pay",
          name: "可付款",
          type: "checkbox",
          required: false,
          options: {},
        },
        {
          id: "bsf_invoice_notes",
          slug: "review_notes",
          name: "审核备注",
          type: "longtext",
          required: false,
          options: {},
        },
        {
          id: "bsf_invoice_ai_summary",
          slug: "ai_summary",
          name: "AI摘要",
          type: "ai_summary",
          required: false,
          options: {
            ai: {
              model: "gpt-5-mini",
              reviewRequired: true,
              sourceFieldIds: ["bsf_invoice_notes"],
            },
          },
        },
      ],
    },
  ],

  records: [
    {
      id: FINANCE_PO_PLATFORM_ID,
      baseId: DEMO_PURCHASE_ORDERS_BASE_ID,
      commitId: PO_PLATFORM_COMMIT_ID,
      fields: {
        approved_at: "2026-05-20",
        budget: 860000,
        currency: "CNY",
        owner: "finance.ops@busabase.local",
        po_number: "PO-2026-0418",
        status: "open",
        vendor: "全球云服务有限公司",
      },
      message: "种子数据：云平台采购订单",
      author: "seed-finance",
      minutesAgo: 170,
      useCases: ["finance"],
    },
    {
      id: FINANCE_PO_DESIGN_ID,
      baseId: DEMO_PURCHASE_ORDERS_BASE_ID,
      commitId: PO_DESIGN_COMMIT_ID,
      fields: {
        approved_at: "2026-05-28",
        budget: 120000,
        currency: "CNY",
        owner: "design.ops@busabase.local",
        po_number: "PO-2026-0472",
        status: "matched",
        vendor: "飞捷设计软件",
      },
      message: "种子数据：设计软件采购订单",
      author: "seed-finance",
      minutesAgo: 168,
      useCases: ["finance"],
    },
    {
      id: FINANCE_INVOICE_GLOBEX_ID,
      baseId: DEMO_INVOICES_BASE_ID,
      commitId: INVOICE_GLOBEX_COMMIT_ID,
      fields: {
        ai_summary: "云服务发票在已审批采购订单范围内，但需财务审核税项和服务周期备注。",
        amount: 812000,
        due_date: "2026-07-05",
        flags: ["po-match", "tax-check"],
        invoice_file: [
          {
            id: "att_seed_invoice_globex_pdf",
            attachmentId: "att_seed_invoice_globex_pdf",
            fileName: "globex-cloud-invoice-2026-06.pdf",
            mimeType: "application/pdf",
            size: 624_128,
            url: "/assets/readme/scenarios/finance-review-base.png",
          },
        ],
        invoice_number: "INV-GCX-2026-0618",
        "purchase-order": [FINANCE_PO_PLATFORM_ID],
        ready_to_pay: false,
        review_notes: "OCR已匹配供应商、采购单号、账期和小计。税额行需财务部门审批确认。",
        status: "needs-review",
        tax: 65000,
        total: 877000,
        vendor: "全球云服务有限公司",
      },
      message: "种子数据：待AP三方比对的发票",
      author: "seed-finance",
      minutesAgo: 120,
      useCases: ["finance"],
    },
    {
      id: FINANCE_INVOICE_FIGMA_ID,
      baseId: DEMO_INVOICES_BASE_ID,
      commitId: INVOICE_FIGMA_COMMIT_ID,
      fields: {
        ai_summary: "设计软件发票与采购订单匹配，可直接付款。",
        amount: 115000,
        due_date: "2026-07-10",
        flags: ["po-match"],
        invoice_file: [
          {
            id: "att_seed_invoice_figma_png",
            attachmentId: "att_seed_invoice_figma_png",
            fileName: "figma-seats-invoice.png",
            mimeType: "image/png",
            size: 218_944,
            url: "/assets/readme/scenarios/finance-review-record.png",
          },
        ],
        invoice_number: "INV-FIG-2026-0441",
        "purchase-order": [FINANCE_PO_DESIGN_ID],
        ready_to_pay: true,
        review_notes: "席位数量、供应商名称和年度合同日期与已审批的采购订单一致。",
        status: "matched",
        tax: 0,
        total: 115000,
        vendor: "飞捷设计软件",
      },
      message: "种子数据：已匹配的设计软件发票",
      author: "seed-finance",
      minutesAgo: 118,
      useCases: ["finance"],
    },
  ],

  views: [
    {
      id: "viw_seed_invoice_review",
      baseId: DEMO_INVOICES_BASE_ID,
      slug: "needs-ap-review",
      name: "待财务审核",
      description: "有异常、税务核查或缺少付款审批的发票。",
      config: {
        filters: [{ fieldSlug: "status", operator: "equals", value: "needs-review" }],
        sorts: [{ direction: "asc", fieldSlug: "due_date" }],
        visibleFieldSlugs: [
          "invoice_number",
          "vendor",
          "purchase-order",
          "total",
          "due_date",
          "flags",
          "ready_to_pay",
        ],
      },
      minutesAgo: 110,
      useCases: ["finance"],
    },
  ],

  changeRequests: [
    {
      id: FINANCE_INVOICE_REVIEW_ID,
      baseId: DEMO_INVOICES_BASE_ID,
      status: "in_review",
      submittedBy: "ap-reconcile-agent",
      sourceMeta: { seed: true, scenario: "invoice-three-way-match", workflow: "ap-review" },
      minutesAgo: 6,
      useCases: ["finance"],
      operations: [
        {
          id: "opr_seed_invoice_three_way_match",
          commitId: "cmt_seed_invoice_three_way_match",
          operation: "record_update",
          targetRecordId: FINANCE_INVOICE_GLOBEX_ID,
          baseCommitId: INVOICE_GLOBEX_COMMIT_ID,
          fields: {
            ai_summary:
              "三方比对通过：供应商、采购订单、小计、税额和服务周期均已核实，可提交付款审批。",
            amount: 812000,
            due_date: "2026-07-05",
            flags: ["po-match"],
            invoice_file: [
              {
                id: "att_seed_invoice_globex_pdf",
                attachmentId: "att_seed_invoice_globex_pdf",
                fileName: "globex-cloud-invoice-2026-06.pdf",
                mimeType: "application/pdf",
                size: 624_128,
                url: "/assets/readme/scenarios/finance-review-base.png",
              },
            ],
            invoice_number: "INV-GCX-2026-0618",
            "purchase-order": [FINANCE_PO_PLATFORM_ID],
            ready_to_pay: true,
            review_notes: "已与PO-2026-0418匹配。税额行与合同条款一致，请批准纳入七月付款批次。",
            status: "matched",
            tax: 65000,
            total: 877000,
            vendor: "全球云服务有限公司",
          },
          message: "审批已匹配发票，纳入七月付款批次",
          author: "ap-reconcile-agent",
        },
      ],
    },
  ],
};
