import type { AirAppDemoDef } from "./demo-content";

const jsonFile = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

export const AIRAPP_DEMO_FUMADOCS: AirAppDemoDef = {
  slug: "demo-fumadocs",
  name: "Fumadocs Documentation",
  description:
    "A real Next.js 16 documentation site generated from MDX by Fumadocs, with a sidebar and two routed pages. Requires a Sandock Remote machine.",
  files: [
    {
      path: "airapp.json",
      content: jsonFile({
        runtime: "node",
        install: "npm install",
        start: "npm run dev",
        port: 3000,
        requiredEngine: "remote",
      }),
    },
    {
      path: "package.json",
      content: jsonFile({
        name: "fumadocs-airapp-demo",
        version: "0.1.0",
        private: true,
        scripts: {
          dev: `next dev --hostname 0.0.0.0 --port \${PORT:-3000}`,
          postinstall: "fumadocs-mdx",
        },
        dependencies: {
          "@tailwindcss/postcss": "4.3.3",
          "@types/mdx": "2.0.13",
          "@types/node": "26.3.0",
          "@types/react": "19.2.17",
          "@types/react-dom": "19.2.3",
          "fumadocs-core": "16.14.5",
          "fumadocs-mdx": "15.3.0",
          "fumadocs-ui": "16.14.5",
          next: "16.3.3",
          react: "19.2.7",
          "react-dom": "19.2.7",
          tailwindcss: "4.3.3",
          typescript: "7.0.2",
        },
      }),
    },
    {
      path: "next.config.mjs",
      content: `import { createMDX } from "fumadocs-mdx/next";

const withMDX = createMDX();

/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,
};

export default withMDX(config);
`,
    },
    {
      path: "source.config.ts",
      content: `import { defineConfig, defineDocs } from "fumadocs-mdx/config";

export const docs = defineDocs({
  dir: "content/docs",
});

export default defineConfig();
`,
    },
    {
      path: "postcss.config.mjs",
      content: `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`,
    },
    {
      path: "tsconfig.json",
      content: jsonFile({
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "react-jsx",
          incremental: true,
          plugins: [{ name: "next" }],
          paths: {
            "@/*": ["./src/*"],
            "fumadocs-mdx:collections/*": ["./.source/*"],
          },
        },
        include: [
          "next-env.d.ts",
          "**/*.ts",
          "**/*.tsx",
          ".next/types/**/*.ts",
          ".next/dev/types/**/*.ts",
        ],
        exclude: ["node_modules"],
      }),
    },
    {
      path: "next-env.d.ts",
      content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and should not be edited.
`,
    },
    {
      path: "src/app/global.css",
      content: `@import "tailwindcss";
@import "fumadocs-ui/css/neutral.css";
@import "fumadocs-ui/css/preset.css";

html {
  letter-spacing: 0;
}

body {
  margin: 0;
}
`,
    },
    {
      path: "src/app/layout.tsx",
      content: `import type { Metadata } from "next";
import type { ReactNode } from "react";
import { RootProvider } from "fumadocs-ui/provider/next";
import "./global.css";

export const metadata: Metadata = {
  title: {
    default: "Fumadocs AirApp",
    template: "%s | Fumadocs AirApp",
  },
  description: "A runnable Fumadocs example inside Busabase.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
`,
    },
    {
      path: "src/app/page.tsx",
      content: `import { redirect } from "next/navigation";

export default function HomePage() {
  redirect("/docs");
}
`,
    },
    {
      path: "src/app/docs/layout.tsx",
      content: `import { DocsLayout } from "fumadocs-ui/layouts/docs";
import type { ReactNode } from "react";
import { source } from "@/lib/source";

export default function DocumentationLayout({ children }: { children: ReactNode }) {
  return (
    <DocsLayout
      tree={source.pageTree}
      nav={{
        title: "Fumadocs AirApp",
      }}
    >
      {children}
    </DocsLayout>
  );
}
`,
    },
    {
      path: "src/app/docs/[[...slug]]/page.tsx",
      content: `import { createRelativeLink } from "fumadocs-ui/mdx";
import { DocsBody, DocsDescription, DocsPage, DocsTitle } from "fumadocs-ui/page";
import { notFound } from "next/navigation";
import { source } from "@/lib/source";
import { getMDXComponents } from "@/mdx-components";

export default async function DocumentationPage({
  params,
}: {
  params: Promise<{ slug?: string[] }>;
}) {
  const { slug } = await params;
  const page = source.getPage(slug);
  if (!page) notFound();

  const MDX = page.data.body;

  return (
    <DocsPage toc={page.data.toc}>
      <DocsTitle>{page.data.title}</DocsTitle>
      <DocsDescription>{page.data.description}</DocsDescription>
      <DocsBody>
        <MDX
          components={getMDXComponents({
            a: createRelativeLink(source, page),
          })}
        />
      </DocsBody>
    </DocsPage>
  );
}

export function generateStaticParams() {
  return source.generateParams();
}
`,
    },
    {
      path: "src/lib/source.ts",
      content: `import { docs } from "fumadocs-mdx:collections/server";
import { loader } from "fumadocs-core/source";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
`,
    },
    {
      path: "src/mdx-components.tsx",
      content: `import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...(defaultMdxComponents as unknown as MDXComponents),
    ...components,
  };
}
`,
    },
    {
      path: "content/docs/meta.json",
      content: jsonFile({
        title: "Fumadocs AirApp",
        pages: ["index", "getting-started"],
      }),
    },
    {
      path: "content/docs/index.mdx",
      content: `---
title: Fumadocs AirApp
description: A real MDX documentation site running on a Sandock Remote machine.
---

This site is generated from MDX by Fumadocs and served by Next.js inside an AirApp.

<Cards>
  <Card title="Getting Started" href="/docs/getting-started">
    Follow the short guide and verify that nested documentation routes work.
  </Card>
  <Card title="Edit the source" href="/docs/getting-started#make-it-yours">
    Change an MDX file, restart the AirApp, and see the docs update.
  </Card>
</Cards>

## What this example proves

- Fumadocs generates its collection during \`npm install\`.
- Next.js serves the documentation sidebar and MDX content.
- Sandock exposes both the index route and direct nested routes.
`,
    },
    {
      path: "content/docs/getting-started.mdx",
      content: `---
title: Getting Started
description: Run, navigate, and customize this Fumadocs AirApp.
---

## Run the documentation site

Open this AirApp in Busabase. A Sandock Remote machine installs the pinned dependencies, runs Fumadocs generation, and starts Next.js.

The preview opens at \`/docs\`. Use the sidebar to move between this page and the documentation home.

## Check direct routing

Refresh this page or open \`/docs/getting-started\` directly. The catch-all Next.js route resolves the matching generated MDX page.

## Make it yours

Edit either file under \`content/docs\`, then restart the AirApp. Fumadocs rebuilds the source collection and Next.js renders the updated page.
`,
    },
  ],
};
